### Install Dependencies

In [1]:
import pandas as pd
import openai

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

### Read Sample dataset from Amazon

In [3]:
df_items = pd.read_json("../../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [4]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,AMAZON FASHION,"Bosttor Bluetooth Beanie Hat with Light, Headl...",4.5,2342,"[100% Acrylic, Elastic closure, Hand Wash Only...",[],26.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Beanie Hat with Bluetooth Headphon...,Bosttor,"[Electronics, Headphones, Earbuds & Accessorie...","{'Department': 'unisex-adult', 'Date First Ava...",B0BH41HYFZ,NaN,NaN,NaN
1,All Electronics,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",4.2,148,[【USB or USB C to Ethernet Adapter】The Etherne...,[],14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aceele,"[Electronics, Computers & Accessories, Network...",{'Product Dimensions': '3.54 x 0.98 x 0.71 inc...,B0BKPB2YQ9,NaN,NaN,NaN
2,All Electronics,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,4.2,3331,[📍3-Port HDMI Switch: This aluminum HDMI switc...,[],18.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Darren reviews VWRHAR 3-1 splitter...,VWRHar,"[Electronics, Home Audio, Home Audio Accessori...",{'Package Dimensions': '6.1 x 4.21 x 0.94 inch...,B09MM5QT3R,NaN,NaN,NaN
3,All Electronics,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",3.4,125,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Burxoe,[],{'Package Dimensions': '3.15 x 3.07 x 2.52 inc...,B09Q5TNDHY,NaN,NaN,NaN
4,Cell Phones & Accessories,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",4.7,335,[【Compatible Airpods 1/2 】This case designed f...,[1],11.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'airpod cases', 'url': 'https://www...",UGUHY,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '7.44 x 4.61 x 1.57 inc...,B0BZJKX7MS,NaN,NaN,NaN

In [5]:
### Preprocess title and features

def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [6]:
def extract_first_large_image(row):
    return row['images'][0].get('large', '')

In [7]:
df_items['preprocessed_description'] = df_items.apply(preprocess_description, axis=1)
df_items['image_url'] = df_items.apply(extract_first_large_image, axis=1)

In [8]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_description,image_url
0,AMAZON FASHION,"Bosttor Bluetooth Beanie Hat with Light, Headl...",4.5,2342,"[100% Acrylic, Elastic closure, Hand Wash Only...",[],26.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Beanie Hat with Bluetooth Headphon...,Bosttor,"[Electronics, Headphones, Earbuds & Accessorie...","{'Department': 'unisex-adult', 'Date First Ava...",B0BH41HYFZ,NaN,NaN,NaN,"Bosttor Bluetooth Beanie Hat with Light, Headl...",https://m.media-amazon.com/images/I/51b7qcj8dZ...
1,All Electronics,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",4.2,148,[【USB or USB C to Ethernet Adapter】The Etherne...,[],14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aceele,"[Electronics, Computers & Accessories, Network...",{'Product Dimensions': '3.54 x 0.98 x 0.71 inc...,B0BKPB2YQ9,NaN,NaN,NaN,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",https://m.media-amazon.com/images/I/41WsGRr-3T...
2,All Electronics,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,4.2,3331,[📍3-Port HDMI Switch: This aluminum HDMI switc...,[],18.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Darren reviews VWRHAR 3-1 splitter...,VWRHar,"[Electronics, Home Audio, Home Audio Accessori...",{'Package Dimensions': '6.1 x 4.21 x 0.94 inch...,B09MM5QT3R,NaN,NaN,NaN,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,https://m.media-amazon.com/images/I/41fsjaknf1...
3,All Electronics,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",3.4,125,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Burxoe,[],{'Package Dimensions': '3.15 x 3.07 x 2.52 inc...,B09Q5TNDHY,NaN,NaN,NaN,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",https://m.media-amazon.com/images/I/51YFypeuZh...
4,Cell Phones & Accessories,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",4.7,335,[【Compatible Airpods 1/2 】This case designed f...,[1],11.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'airpod cases', 'url': 'https://www...",UGUHY,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '7.44 x 4.61 x 1.57 inc...,B0BZJKX7MS,NaN,NaN,NaN,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",https://m.media-amazon.com/images/I/41V7Wi2ckb...

In [9]:
### Sample items from dataset
df_sample = df_items.sample(n=50, random_state=7)

In [10]:
df_data_to_embed = df_sample[['preprocessed_description', 'image_url', 'rating_number', 'price', 'average_rating', 'parent_asin', ]]

In [11]:
data_to_embed = df_data_to_embed.to_dict(orient = "records")

In [12]:
data_to_embed

[{'preprocessed_description': 'MANDDDWU 80x100 Monocular-Telescope Low Night Vision Monoculars High Definition for Adults High Powered with Smartphone Adapter Telescope Hunting Wildlife Bird Watching Travel Camping Hiking ',
  'image_url': 'https://m.media-amazon.com/images/I/51h4NUuSazL._AC_.jpg',
  'rating_number': 446,
  'price': 29.99,
  'average_rating': 3.8,
  'parent_asin': 'B09QQ2J8XN'},
 {'preprocessed_description': 'Car Windshield Dashboard Tablet Holder for 5.5-12.9" Tablet Smartphone, EXSHOW Long Arm Suction Cup Car Window Tablet Cell Phone Mount for iPad Pro Air Mini, Samsung Galaxy Tab, iPhone, Xiaomi etc ',
  'image_url': 'https://m.media-amazon.com/images/I/41k1INUbfAL._AC_.jpg',
  'rating_number': 103,
  'price': nan,
  'average_rating': 4.0,
  'parent_asin': 'B08DLWKXGL'},
 {'preprocessed_description': 'SOOMFON Bluetooth 5.0 FM Transmitter for Car, Stronger Microphone & Bass Sound Bluetooth Radio Transmitter Car Adapter, Support 20W PD+QC3.0, 7 Colors LED Backlit, Wireless Call, AUX Output & U Disk 【Hi-Fi & Deep Bass Sound】SOOMFON Bluetooth car adapter with powerful bass-driven tech, you can enjoy 100% more bass than ordinary Bluetooth FM transmitter via the Long press of the "Light switch"button, display show b0 means normal. b1 means bass boost. High speed noise cancellation and BASS sound selection bring you more choice to enjoy music feast. 【QC3.0 & PD 20W Type C Fast Charging Ports】SOOMFON Bluetooth car adapter is designed with 2 quick charging ports, QC3.0 and PD 3.0 20W Type C port, which can provide 4X faster speeding than normal charging port. You can simultaneously charge 2 compatible devices. 【HANDS-FREE CALLING】A highly sensitive in-build microphone picks up your voice nicely and removes the background noises with the help of CVC Noise cancellation technology, phone calls are clear and easy to hear both in the vehicle and by the caller. Since you can pick and reject calls with the press of a button, you will surely enjoy a crystal clear hands-free calling experience with it! 【LEVER UP YOUR DRIVING EXPERIENCE】 It helps to monitor car voltage, and features a ring light around the shell, which is useful for quickly finding it in the dark and provides some necessary flair to your car. This FM transmitter Bluetooth for car streams any audio from your phone to the car system, including navigation and voice assistant, bringing your old and vintage car to a new lever 【Safe Protections & Universal Bluetooth Car Adapter】Passed CE, FCC and RoHS certifications. Multiple protections for overcurrent, overvoltage, overload, overheat and short circuit. Compatible with most smartphones and Bluetooth-enabled devices. Such as iPhone/iPad Pro/Samsung/Google/MP3 player/Android phone. Fit 12-24V car cigarette lighter (car, suv, truck, etc.) 【WHAT YOU WILL GET】SOOMFON Car Bluetooth Radio Transmitter*1, User Guide*1. Note: Please find an unused car radio frequency, if the frequency is not occupied, it will emit a slight steady rustling sound. Adjust the product\'s FM frequency to be the same as the car\'s FM frequency (the car radio will be quiet, if it\'s still not quiet, retry a new blank channel on the car radio).',
  'image_url': 'https://m.media-amazon.com/images/I/41lERfK8e7L._AC_.jpg',
  'rating_number': 100,
  'price': 11.88,
  'average_rating': 4.4,
  'parent_asin': 'B0C6MJL8D8'},
 {'preprocessed_description': 'Besoar for AirPods Pro 2019/Pro 2 Case 2022 Cartoon Cute Kawaii Silicone Cases for Apple AirPod Air Pods Pro Design Character Cover Cool Unique Fashion Fun Funny Soft Coves for Girls Girly Boys(Bunny) Compatible With: Only suitable for Airpods Pro 2019/Pro 2 generation Case 2022, it fits perfectly with the Airpods Pro, and the precise opening position makes it easy to use the charging port, take out and put in the headset. High Quality Material: The protective cases designed for Airpod Pro 2019/Pro 2 generation 2022 are made of soft durable silica gel. The rubber surface will not fade during long-term use.it is not easy to be torn and deformed. Aesthetic Design: This cute cartoon stylish and unique AirPods earphone protective shell is colorful and interesting in shape, fashionable and popular. Lightweight and thin, comfortable to touch. Comprehensive Protection: The silicone cases protect your Air Pod Pro 2019/Pro 2 generation 2022 from scratching, will not let sharp objects leave scratches on the Air Pod Pro surface. Sturdy shell can prevent your earphone from being damaged by accidental drops. Nice Gift: This stylish and trendy AirPods protective case is suitable for friends and family around you. It is a very good gift for birthdays, Christmas, Halloween, Thanksgiving and other holidays.',
  'image_url': 'https://m.media-amazon.com/images/I/41IdwBqczDL._AC_.jpg',
  'rating_number': 328,
  'price': 11.99,
  'average_rating': 4.5,
  'parent_asin': 'B0BLYCBGMF'},
 {'preprocessed_description': '80x100 Monocular-Telescope Low Night Vision Monoculars High Definition for Adults High Powered with Smartphone Adapter Monocular Telescope Hunting Wildlife Bird Watching Travel Camping Hiking ',
  'image_url': 'https://m.media-amazon.com/images/I/51Ni+NLJS4L._AC_.jpg',
  'rating_number': 187,
  'price': 29.99,
  'average_rating': 3.6,
  'parent_asin': 'B09YHBXZC8'},
 {'preprocessed_description': "Smart Watch, Tykoit Smartwatch 41mm with Heart Rate Monitor & Sleep Tracking & SpO2, IP68 Waterproof Fitness Tracker with Step/Calorie Counter Compatible with Android and iOS Phones Heart Rate, Sleep and SpO2 Monitor: This smart watch built in high performance motion sensor automatically detects your heart rate in real time, and also measure your SpO2 and deep, light sleep state which can help you better understand your health. (NOTE: the data cannot be used as a medical-grade test) All-day Activity Tracking: This smartwatch has 8 kinds of sports modes (walking, running, treadmill, bicycle, yoga and other workouts). The fitness tracker display shows your accurate steps, distance, calories, active minutes and you can also see more detailed data on App. Customizable Watch Face: Our smartwatches support customizable watch faces with your favorite pictures to suit your daily mood and occasion. And the fitness watch with 1.4 inch color full touchscreen display for exceptional hd quality, making it easy and quick to view time and date. Smart Notifications and More Practical Features: All messages and notifications will show on your wrist and remind you through vibration. It cannot answer call or text on sports watch. There are also many convenient functions like Timer, Stopwatch, Wake-up Gesture, Find Phone, Sedentary Reminder and Music Control. Long-lasting Battery Life & IP68 Waterproof: The smartwatches could last about 10 days when in auto monitoring mode for heart rate or 7 days when in the instant detection mode. Our active watch is designed with IP68 waterproof standards, protect yourself against sweating, rainning, and other water splashes. Also can wear it without worries while swimming(Please note: This device can't track your swimming data).",
  'image_url': 'https://m.media-amazon.com/images/I/41fLyn2USrL._AC_.jpg',
  'rating_number': 299,
  'price': nan,
  'average_rating': 4.1,
  'parent_asin': 'B09SNWJC5N'},
 {'preprocessed_description': "KEEPXYZ Genuine Leather Airtag Holder Suitable for Apple Airtag Keychain Leather, Small Air Tag Holder with Key Rings, Protective Airtag Case Cover Accessories - Black V1.0 [Compatibility] The full coverage secure Leather airtag holder is compatible with Apple AirTag 2021. (Note: Airtag is not included.) It'll be excellent air tags mate for luggage when you out for travel. [Genuine Leather] Compared to cheap pu leather or faux leather, our airtag case is made from genuine leather, which is more durable. [Discreet Design] The air tag holder is designed in Integrated Structure and Double Anti-Loss Structure. The main body is molded from a complete piece of leather. The top position where the metal key ring goes thru is not cut off or separated. The airtag entrance is locked by a metal snap, and an additional little leather loop outside. Perfect to anti-lost for kids, elders and pets. [Handmade Crafts] The airtag case is hand made and polished by professional craftsmen. Every production process and every product detail is controllable. Never lose the apple airtag tracker orginal beauty while ensuring practicality. [Intimate Accessories] The airtag accessories set comes with 1 leather airtag holder with metal snap, 2 key rings, and 1 little leather loop. The 2 different key rings are convenient to choose freely according to your preferences, the leather loops and metal snap are more effective to lock the entrance to prevent airtag from being lost.",
  'image_url': 'https://m.media-amazon.com/images/I/41Uv4x1rnQL._AC_.jpg',
  'rating_number': 2247,
  'price': 12.95,
  'average_rating': 4.8,
  'parent_asin': 'B0B9L1N68J'},
 {'preprocessed_description': 'Anlink 4K 8MP 5MP 2MP 1080P 100FT/30M Premade 2-in-1 BNC Video Power Cable/Wire for Security Camera Systems, CCTV, DVR, Surveillance System, with BNC Connector and RCA Adapter (Black) 【2-in-1& plug-and-play】The 2-in-1 video&power BNC cable simplifies the installation of surveillance system by using one cable to transmit HD video and provide safe power supply. With BNC connector and RCA adapter, it is well adaptive for application and easy to install. 【Premium material & high quality】Made of premium pure copper material and PVC-45P molding, the cable is with lower resistivity and better electrical conductivity, weatherproof and durable. 【High compatibility】The cable is well compatible with all brand surveillance DVR camera system, 960H/720P/960P/1080P/3MP/4MP/5MP/6MP/8MP(4K), AHD/CVI/TVI cameras. Notice: For video cameras with 2.1mm DC power connectors only. 【ISET s. r. l Certified】The Cable is with 5.5*2.1*10mm standard DC power connector and the standard video DC power supply meets the ISET s. r. l communication cable standard. 【One-stop service】The package comes with 1*100ft/30m video& power 2-in-1 cable, 1*BNC to BNC connector, 1*BNC to RCA connector, user manual. Anlink provides quick help, 1-year Warranty and lifetime technical support.',
  'image_url': 'https://m.media-amazon.com/images/I/41D3jduu4uL.jpg',
  'rating_number': 102,
  'price': 11.99,
  'average_rating': 4.6,
  'parent_asin': 'B0BJ8SQBKH'},
 {'preprocessed_description': "iPhone Charger Cable 3Pack 6FT, [Apple MFi Certified] Lightning Cable Cord Nylon Braided iPhone Charger Fast Charging Compatible with iPhone 14 13 12 11 Pro Max XR XS X 8 7 6 Plus SE/iPad 【Fast Charge & Data Transfer】-iPhone charger cable is made of high-purity copper core and intelligent chip, with overcharge protection, stable current protection, automatic switching, and battery protection, and can support up to 2.4A fast charging and 480 Mbps transfer speed. 【Apple Mfi Certified】-Certified by MFI and original 8 Pin connector with a fast Charging end, ensured safe charging for your devices. Enjoy fast charge and data transfer. 【Super Durability & Flexibility】- iphone charger cable with premium double shade braided nylon body to ensure it's super durability and strength.The polished aluminum alloy case not only fits your iPhone perfectly, but also prevents physical compression. 【Compatible Models】-Lightning cable compatible with iPhone 13/12/ 11 / 11 Pro / 11 Pro Max / XS / XS Max / XR / X / 8 Plus / 8 / 7 Plus / 7 / 6s Plus / 6s / 6 Plus / 6 / 5s / 5c / 5 /Air 2 /mini / mini 2 / mini 4 and More. 【Perfect Lengths】: Perfect 6feet extra long iphone charger cable free up your charging time, no more being stuck to wall socket, ideal for using at home, in car and office.",
  'image_url': 'https://m.media-amazon.com/images/I/51b5PWBP3EL._AC_.jpg',
  'rating_number': 362,
  'price': 8.99,
  'average_rating': 4.5,
  'parent_asin': 'B0C93Q4CPK'},
 {'preprocessed_description': 'Micro SD Card 512GB Micro Memory SD Cards with A Free SD Card Adapter,TF Card 512GB Memory Card 512GB Fast Speed for Camera/Android Phones [Stable]Memory card is made from high-quality chips, offer reliable performance, ensuring evidence is clearly recorded in full HD without dropped frames. [Durable]Memory cards are temperature waterproof, shock-proof, temperature proof, magnet and x-ray. [High Speed]Memory card up to 15MB/s read speed,write speed is 10MB/s.Based on internal testing; performance may be lower depending on host device, interface, usage conditions and other factors. [Compatibility]Memory card is compatible with computer, laptop,tablet,smartphones,pad,dash cam, camcorder,surveillance,e-reader,drone. [Store]Up to 512GB to store even more hours of Full HD video 1GB=1,000,000,000 bytes. It will vary based on host device,file attributes.',
  'image_url': 'https://m.media-amazon.com/images/I/41A8f8KK5cL._AC_.jpg',
  'rating_number': 101,
  'price': 11.99,
  'average_rating': 3.8,
  'parent_asin': 'B0BTDCBWQ6'},
 {'preprocessed_description': "50 Pcs Stickers for Water Bottles, Cute Vinyl Waterproof Aesthetic Stickers，Hydroflask Laptop Phone Skateboard Stickers for Kids, Teens, Adults(Cute Cartoon Cat) ❤️Cute Stickers: Every sticker pack contains 50 pieces of different stickers. There is no random delivery and no duplicates, our cute stickers can bring a lot of fun to your life. Each sticker measures about 2-3 inches.. ❤️Safe and Non-Toxic: Each sticker is made of vinyl, using 100% brand new high-definition printing, the pattern is clearer and more vivid and each waterproof sticker are in perfect size. The sticker can be stuck on repeatedly and the adhesive can be torn off without any residues. ❤️Adorable Decorations: Our kids stickers are suitable for dressing up various items such as laptops, computers, kettles, water bottles, hydroflask, mirrors, notebooks, diaries, luggage, skateboards, snowboards, bicycles, cars and anything you want to decorate. ❤️Fantastic Gifts: Our cute and cool stickers are designed for kids, teens and even adults. It's a good chioce as birthday gifts and as rewards for students. ❤️After-sale Service: If you have any questions about our stickers when you receive them, please feel free to contact us by email. We'll do our best to solve your problem in 24-hour business day.",
  'image_url': 'https://m.media-amazon.com/images/I/61LPE-iLgQL._AC_.jpg',
  'rating_number': 273,
  'price': 5.59,
  'average_rating': 4.5,
  'parent_asin': 'B0B1CY7TV2'},
 {'preprocessed_description': 'Geiomoo Silicone Case Compatible with Bose QuietComfort Earbuds II, Protective Cover with Carabiner (White) Perfectly matches with Bose QuietComfort Earbuds II Made of high quality soft silicone, scratch proof, shock proof and durable Carabiner is included to improve the practicality 360° all-round protection Easy to install',
  'image_url': 'https://m.media-amazon.com/images/I/31yJ0EyEn1L._AC_.jpg',
  'rating_number': 115,
  'price': 6.65,
  'average_rating': 4.3,
  'parent_asin': 'B0BHSPRXLR'},
 {'preprocessed_description': 'TCL 65-Inch Q7 QLED 4K Smart TV with Google TV (65Q750G, 2023 Model) Dolby Vision, Dolby Atmos, HDR Ultra, 120Hz, Game Accelerator up to 240Hz, Voice Remote, Works with Alexa, Streaming UHD Television 4K Ultra HD Resolution: Experience incredible detail with 4X the resolution of 1080p Full HDTVs. QLED – Quantum Dot Technology with UltraWide Color Gamut: Enjoy over a billion colors for richer and more lifelike images. HighBright PRO Direct LED Backlight: With up to 1,000 Nits peak brightness, Q7 models create bright images with dazzling specular highlights, for a truly immersive and realistic cinematic experience. Full Array PRO Local Dimming: Enjoy superior contrast with up to 200+ local dimming zones that dynamically adapt to on-screen content, for deep blacks without image blooming. 120Hz Panel Refresh Rate: Watch action-packed movies, fast-paced video games, and live sports with an ultra-smooth viewing experience, free of motion blur. Motion Rate 480 with MEMC Frame Insertion: Combines multiple motion enhancement technologies for best-in-class motion clarity Game Accelerator 240: With up to blistering fast 240Hz VRR, enjoy more responsive gameplay without lag, designed to keep you at the top of any leaderboard. HDR ULTRA (Dolby Vision IQ, HDR10+, HDR10, & HLG): Enjoy enhanced contrast, accurate colors and fine details utilizing all the most advanced HDR formats. TCL AIPQ Engine with Deep Learning AI: Powerful, 3rd-generation advanced processor intelligently optimizes the color, contrast, and clarity for an unrivaled 4K HDR experience. Google TV Smart OS with Hands-Free Voice Control and Backlit Voice Remote – The entertainment you love. Google TV brings your favorite movies, shows, and live shows together.',
  'image_url': 'https://m.media-amazon.com/images/I/41pV3k2s2FL._AC_.jpg',
  'rating_number': 130,
  'price': 799.99,
  'average_rating': 4.3,
  'parent_asin': 'B0C5YFBMCX'},
 {'preprocessed_description': '(2 Pack) BGAANM Silicone Earbuds Case Protective Cover with Keychain Fit for Samsung Galaxy Buds2 Pro (2022) /Galaxy Buds 2 (2021) /Galaxy Buds Pro (2021) /Galaxy Buds Live (2020) Silicone Cases Fit Designed for Samsung Galaxy Buds2 Pro (2022) /Galaxy Buds 2 (2021) /Galaxy Buds Pro (2021) /Galaxy Buds Live (2020) - Cartoon pattern skin, multiple elements very stylish and unique, carry it with you, make you look different. Unique Design and Fashion Elements - Cartoon pattern skin and Keychain, multiple elements very stylish and unique, carry it with you, make you look different. At the same time, this is also the best gift for family and friends. Premium Silicone Case Cover- This is made of silicone material, collocation different colors and skin, give your Galaxy buds live full body protection.★they fit Samsung Galaxy Buds2 Pro (2022) /Galaxy Buds 2 (2021) /Galaxy Buds Pro (2021) /Galaxy Buds Live (2020). Precise Cutouts&Durable - Easy installation, adsorption strength fastening and wear it firmly. A charging port is reserved at the bottom of the case,which can be charged without disassembling the case,and it is thin and light, you can easily open or close the lid with your hands. After Sales Service – Our #1 concern is your satisfaction, send us a message us through your Order page and we’ll get back to you faster within 24 hours.',
  'image_url': 'https://m.media-amazon.com/images/I/41KpsjRT6bL._AC_.jpg',
  'rating_number': 230,
  'price': 13.99,
  'average_rating': 4.5,
  'parent_asin': 'B09QQ11NQY'},

### Define embedding function

In [13]:
from google import genai
from google.genai import types
import os

gemini_client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))
result = gemini_client.models.embed_content(
    model="gemini-embedding-001",
    contents="random text",
    config=types.EmbedContentConfig(task_type="SEMANTIC_SIMILARITY")
)

In [25]:
len(result.embeddings[0].values)

3072

In [ ]:
### Other task_type = SEMANTIC_SIMILARITY, CLASSIFICATION, CLUSTERING, RETRIEVAL_DOCUMENT, CODE_RETRIEVAL_QUERY, QUESTION_ANSWERING, FACT_VERIFICATION

def get_embeddings(text, task_type="SEMANTIC_SIMILARITY", model="gemini-embedding-001"):
    result = gemini_client.models.embed_content(
        model=model,
        contents=text,
        config=types.EmbedContentConfig(task_type=task_type)
    )
    return result.embeddings[0].values

In [27]:
get_embeddings("random text")

[-0.01684018,
 0.018565726,
 0.0068769087,
 -0.06927192,
 -0.00553585,
 0.010261666,
 0.011438973,
 0.004223627,
 0.012219261,
 0.0132948095,
 0.0062436694,
 -0.010938613,
 -0.021939095,
 0.04920108,
 0.11680988,
 0.0032733437,
 -0.02397843,
 0.023174794,
 0.002537348,
 -0.018138312,
 -0.0015183971,
 0.0076536317,
 -0.0009793843,
 -0.015984554,
 -0.015191916,
 -0.017045336,
 0.029863806,
 0.016304195,
 0.02727329,
 -0.0073262565,
 -0.005536062,
 0.033683773,
 0.0033344007,
 0.00010679571,
 0.013984189,
 0.01484251,
 0.022953782,
 0.016573895,
 0.0063176355,
 0.046974257,
 -0.0121840425,
 -3.0958377e-05,
 0.00045738928,
 -0.0030470006,
 0.02308657,
 0.011519489,
 0.004947156,
 -0.007096894,
 0.01923382,
 0.035404667,
 -0.014046564,
 -0.009017905,
 0.004565115,
 -0.15831394,
 -0.0008534757,
 0.0087582795,
 -0.006312307,
 0.0020324066,
 0.012475935,
 0.012627499,
 -0.030367404,
 0.026159406,
 -0.030088518,
 -0.027111536,
 0.01753244,
 -0.022347193,
 0.008908948,
 -0.0077574877,
 -0.04077718,
 0.0040423214,
 -0.014346615,
 -0.0058770548,
 0.005064889,
 -0.006322774,
 0.007029585,
 -0.04386732,
 0.015407353,
 0.011880278,
 0.010684321,
 0.019804658,
 -0.0062310025,
 -0.018087488,
 -0.011172109,
 0.00046840805,
 0.012325458,
 -0.01351078,
 -0.027348518,
 -0.0034924806,
 -0.016591622,
 0.001845193,
 0.012087135,
 0.0035921005,
 0.01406139,
 0.017303096,
 -0.03491758,
 0.0101011945,
 -0.01451877,
 0.021650473,
 -0.0029257734,
 -0.0015960544,
 -0.00047904797,
 -0.023034163,
 -0.027964894,
 -0.016730988,
 0.0016754309,
 -0.012378837,
 0.0028315098,
 -0.0061243847,
 -0.0018171755,
 0.02152908,
 -0.013390141,
 0.014280928,
 -0.003908618,
 0.0151563985,
 0.017017795,
 -0.174355,
 0.01732714,
 0.011230163,
 -0.011151852,
 0.0165453,
 0.00061852136,
 0.011659811,
 0.01574818,
 0.019751253,
 0.0062462375,
 0.00048153984,
 0.027268548,
 -0.011216499,
 0.00012788762,
 0.010443962,
 0.011023096,
 -0.009285595,
 0.0075759874,
 0.020033997,
 -0.013443509,
 0.0214653,
 -0.0088361725,
 0.016587246,
 0.014946487,
 -7.771307e-06,
 0.028101731,
 0.031870037,
 -0.0044578337,
 0.011405472,
 -0.015289038,
 0.0024620711,
 -0.015696771,
 0.030011753,
 0.0050998963,
 -0.017655412,
 -0.022179656,
 -0.014958974,
 -0.02696579,
 0.0006082388,
 0.014482602,
 -0.083042726,
 -0.009197557,
 0.019775657,
 0.022154508,
 -0.013764822,
 -0.00673806,
 0.0021569105,
 0.010040629,
 0.0009933289,
 0.008024537,
 -0.0119356485,
 -0.0024209225,
 -0.015446621,
 0.0142396055,
 0.0022619234,
 -0.01580991,
 -0.018046703,
 0.006137336,
 0.026486853,
 -0.0065363673,
 0.0012087122,
 0.008236813,
 -0.004718654,
 0.00070169155,
 0.0040125786,
 0.0018056768,
 -0.0035029585,
 0.00029674842,
 -0.015536896,
 0.0013218598,
 -0.0039978274,
 -0.012419782,
 -0.02403141,
 0.022659734,
 -0.0039349524,
 -0.0027768482,
 0.02097188,
 0.018343173,
 -0.014536323,
 0.0121749705,
 0.016049093,
 0.009363821,
 0.010143927,
 0.022748852,
 0.0011651784,
 -0.0001170719,
 0.020308588,
 0.03477367,
 0.000799908,
 0.024409007,
 -0.01219172,
 -0.008168534,
 -0.007893082,
 0.010538643,
 0.02250748,
 0.026000828,
 0.0034163054,
 0.0029009378,
 -0.0035227449,
 0.015481212,
 0.015424633,
 -0.008351498,
 -0.0048516616,
 0.0027397873,
 -0.012479412,
 0.018402083,
 -0.0076205432,
 0.006857958,
 0.02063928,
 -0.0036312535,
 0.008636386,
 -0.010536327,
 -0.012479294,
 -0.01812684,
 0.0033920049,
 -0.021403497,
 0.034836788,
 -0.019592276,
 0.0013059741,
 -0.0064183166,
 0.0112871,
 -0.012323769,
 0.024490312,
 0.008307579,
 -0.023761988,
 -0.015850306,
 -0.022464342,
 0.021395272,
 0.026200332,
 0.006729121,
 -0.01992921,
 -0.004344169,
 0.006263866,
 -0.0051832628,
 0.0064220303,
 0.0076840064,
 -0.00024186252,
 0.0118476795,
 -0.01633287,
 -0.0056463126,
 -0.0029129065,
 -0.0287855,
 -0.023605708,
 0.0029936475,
 -0.022403538,
 -0.020596467,
 -0.020279914,
 0.011978912,
 -0.038425285,
 0.0046291295,
 -0.005866427,
 0.019953016,
 0.0073689227,
 -0.013744841,
 0.022494538,
 -0.0030097344,
 -0.0041110385,
 -0.00240264,
 -0.0278593,
 -0.0057754666,
 0.021903478,
 -0.09525192,
 0.02058868,
 0.0068645934,
 0.011730766,
 0.029345248,
 -0.014662915,
 -0.006241494,
 -0.010164994,
 -0.012297306,
 0.018678041,
 0.0013238575,
 -0.0065000486,
 0.014305512,
 -0.0024706065,
 -0.01169597,
 0.024723414,
 -0.005131765,
 -0.006020276,
 0.031531572,
 -0.019316321,
 0.008332516,
 -0.002740517,
 -0.014978106,
 0.02050078,
 -0.015037658,
 0.0068868883,
 -0.008138734,
 0.030300302,
 0.005747651,
 0.019927992,
 0.014124412,
 0.00721509,
 -0.0066106166,
 0.0028706258,
 0.00743158,
 0.021978723,
 0.0065115644,
 0.010361343,
 0.01927314,
 -0.009908402,
 0.0069759204,
 0.006314771,
 0.01457736,
 0.011191795,
 -0.016927475,
 0.008180671,
 -0.022935882,
 0.009154214,
 -0.016275411,
 0.013889553,
 -0.0047218907,
 -0.019226884,
 0.008927489,
 -0.021658918,
 0.0045508454,
 0.009960724,
 0.0024259281,
 -0.00842772,
 -0.0009797284,
 0.0052806623,
 0.00447274,
 0.0051524723,
 -0.0056220326,
 0.017856115,
 0.0034968585,
 0.0045026774,
 -0.013340363,
 -0.00040534156,
 -0.032582536,
 0.015706336,
 0.007100772,
 -0.003930097,
 0.004722014,
 -0.02377025,
 -0.002200528,
 0.010281958,
 -0.025488416,
 0.0012025966,
 -0.025674542,
 0.026041422,
 0.016619721,
 -0.001753783,
 0.001415325,
 0.024964616,
 -0.0031957452,
 -0.0029926926,
 0.015947247,
 0.006113338,
 0.0106034,
 -0.015363124,
 0.013631145,
 -0.00040701425,
 -0.003345345,
 0.01843833,
 -0.0001686088,
 0.0017130537,
 0.01294783,
 0.015476683,
 -0.010655254,
 0.0040733693,
 -0.02250351,
 0.014455137,
 0.015103521,
 0.0037858866,
 -0.0059275916,
 0.0123773115,
 -0.017199313,
 -0.0011416797,
 0.0003289738,
 0.011498552,
 0.008029845,
 -0.0024043072,
 -0.009969778,
 -0.00474876,
 -0.0111508975,
 0.025597466,
 -0.013148769,
 0.016359199,
 -0.019230094,
 -0.012136358,
 -0.011747088,
 -0.0025105604,
 -0.008466258,
 0.008444388,
 -0.00034230188,
 0.0123610385,
 -0.011805894,
 0.0035570876,
 0.005277553,
 0.0030871755,
 -0.002618152,
 -0.013717896,
 -0.011580467,
 -0.0067066113,
 -0.0011804105,
 -0.020534623,
 -0.000655616,
 0.0018757418,
 0.029476658,
 0.015564377,
 -0.022696158,
 -0.025376907,
 0.015414959,
 0.0060395407,
 -0.0005263833,
 0.025494711,
 -0.0051856074,
 0.018638602,
 0.015671898,
 -0.040796425,
 -0.012059021,
 -0.014948325,
 0.01269146,
 -0.018091686,
 0.010767069,
 -0.04279842,
 -0.0042990255,
 -0.013102846,
 -0.004625111,
 -0.0067170905,
 -0.010335177,
 0.0028920255,
 0.0032207812,
 -0.011716392,
 0.017587207,
 0.015221802,
 0.011657107,
 0.01687821,
 0.019589396,
 0.0318378,
 -0.002086321,
 -0.026305208,
 -0.011431576,
 0.0020390986,
 0.0019622522,
 0.011441797,
 0.0051563345,
 0.0036792504,
 0.044304576,
 -0.0053548915,
 -0.026412293,
 0.014581431,
 -0.0017382756,
 0.0066447873,
 -0.019739762,
 -0.0018020202,
 0.0013656599,
 0.003662895,
 -0.006334298,
 0.013099413,
 -0.0046431446,
 -0.022762269,
 -0.005588446,
 0.0060350974,
 0.0025165381,
 0.004408837,
 0.012831569,
 0.007175025,
 -0.012891038,
 0.034797918,
 -0.003217238,
 0.009848171,
 0.010822276,
 -0.00752318,
 -0.009472257,
 -0.009100503,
 0.012630433,
 0.003226978,
 0.004145772,
 0.018811533,
 -0.002362605,
 -0.0013806375,
 -0.017460307,
 0.0051207533,
 0.010864817,
 0.016089944,
 -0.029995216,
 -0.0037215434,
 -0.019292194,
 -0.03964901,
 -0.0020678071,
 -0.022138886,
 0.009485311,
 -0.0068917037,
 0.036093723,
 0.023259645,
 -0.007887515,
 -0.012839969,
 -0.019714331,
 -0.0027566697,
 -0.0020647137,
 -0.009469729,
 -0.015028747,
 -0.028429855,
 0.0032043853,
 -0.006182122,
 0.0063258507,
 0.02426051,
 -0.015772723,
 0.018937092,
 -0.016099805,
 0.04496162,
 -0.0013597965,
 0.023848899,
 0.00035862345,
 0.007996232,
 0.0049547073,
 -0.01197334,
 -0.006608959,
 0.011622773,
 0.013320135,
 0.017504957,
 0.018786622,
 0.0017341858,
 0.0051231226,
 0.030289276,
 -0.022941655,
 -0.015025895,
 -0.004372219,
 0.014325366,
 -0.013652609,
 0.009499296,
 0.017520238,
 0.03271017,
 0.0082180295,
 -0.0006385025,
 -0.0013965636,
 -0.029470095,
 0.0048465054,
 -0.14961855,
 0.019158436,
 -0.0020021216,
 0.011995836,
 0.001187539,
 -0.027794244,
 -0.0055956924,
 -0.017808909,
 0.0064152577,
 0.014181786,
 0.018520065,
 -0.0035426936,
 -0.015104018,
 0.010635373,
 -0.013320012,
 -0.01246013,
 -0.02597126,
 0.02717357,
 0.0007312882,
 -0.016158016,
 -0.010497764,
 0.00978211,
 0.009581659,
 0.008283751,
 -0.0011248216,
 -0.0031116945,
 0.022644643,
 0.02773721,
 -0.01667323,
 0.015445012,
 -0.014646048,
 -0.0063817347,
 0.0039943852,
 0.0084418915,
 0.0048231906,
 -0.016842293,
 0.01055499,
 -0.005230997,
 -0.011328533,
 0.0320021,
 -0.000107437416,
 0.019460073,
 -0.010281553,
 -0.011299362,
 -0.02258098,
 0.018371778,
 0.020909643,
 -0.020709382,
 0.00924146,
 -0.03158776,
 -0.026331108,
 0.020416632,
 0.010247032,
 0.003334427,
 -0.012321514,
 -0.02677624,
 -0.023983777,
 0.023310458,
 -0.014010907,
 -0.0015574424,
 -0.024884228,
 0.0038863744,
 0.0067069265,
 0.013834322,
 -0.0075140535,
 -0.0042108432,
 0.0024964646,
 0.010134866,
 0.015500293,
 -0.009959012,
 0.0034413915,
 -0.0016152939,
 -0.010025909,
 0.021953855,
 0.004847245,
 0.017320141,
 -0.006795157,
 0.01566875,
 -0.020984925,
 -0.006612777,
 -0.0036738808,
 -0.0056482083,
 -0.076065436,
 -0.031313162,
 -0.0038918222,
 0.009278018,
 0.006067193,
 0.0127846515,
 -0.038024306,
 -0.011331449,
 -0.008110804,
 0.0052098203,
 -0.0032339504,
 0.014164401,
 0.007948881,
 -0.006615113,
 0.0030647914,
 0.005248944,
 -0.007411816,
 -0.005221805,
 0.025520079,
 -0.014151698,
 -0.0070748026,
 0.014309136,
 0.0065094037,
 -0.0009366357,
 -0.005212276,
 0.034342654,
 -0.016539663,
 0.0072096833,
 0.010445808,
 -0.018480033,
 -0.017191129,
 -0.12982322,
 -0.0047864597,
 0.0052781776,
 0.019117575,
 0.029692914,
 -0.029842056,
 -0.021011423,
 0.019738715,
 -0.026769765,
 -0.029116184,
 -0.003875357,
 -0.016136983,
 -0.0313336,
 -0.0008488645,
 0.00634528,
 0.14592466,
 -0.017859442,
 0.013170638,
 -0.024259875,
 0.0057841456,
 0.0023718795,
 0.00027385273,
 0.007700907,
 -0.012533215,
 0.018253524,
 0.023293864,
 0.022619769,
 -0.027407266,
 -0.000804384,
 -0.0049849832,
 0.015441865,
 0.0070526265,
 -0.0003420288,
 0.012951776,
 0.0060574464,
 0.005295851,
 0.0033316263,
 -0.011015285,
 0.014963599,
 0.0026099712,
 -0.000107314394,
 0.005349228,
 -0.015797023,
 -0.005694732,
 -0.0040873447,
 0.00645037,
 -0.018087432,
 -0.0074435687,
 -0.010115362,
 0.004582274,
 -0.002921263,
 -0.06532841,
 0.011353147,
 0.038310878,
 0.0031584,
 0.029692287,
 0.0064774645,
 0.014426961,
 0.0059257364,
 0.0033760916,
 -0.0033333122,
 0.0006692382,
 -0.0056998846,
 0.008586657,
 -0.0068535325,
 0.0049951025,
 -0.019619446,
 0.007874038,
 0.0091772005,
 -0.017866388,
 -0.0038135694,
 0.0030906445,
 -0.00021147222,
 0.008768571,
 0.0058552395,
 0.008298929,
 0.0020445217,
 0.0042377166,
 0.007199351,
 0.008172923,
 0.0035205607,
 0.009296423,
 -0.014121918,
 0.003785221,
 0.017219253,
 -0.015727049,
 -0.008131147,
 0.0032903717,
 -0.002400484,
 -0.010257141,
 0.012079929,
 0.014630344,
 0.026790015,
 -0.01907222,
 -0.031275187,
 0.005296499,
 -0.005700257,
 0.0049063195,
 -0.0017068691,
 -0.0041801264,
 -0.00389707,
 -0.010834986,
 0.017127067,
 -0.050084393,
 -0.012774357,
 0.009822149,
 0.0026432495,
 0.004020516,
 0.026666276,
 0.00037108143,
 -0.0040534665,
 -0.015775895,
 0.00061243295,
 -0.0041055325,
 0.0088557815,
 0.0031739718,
 -0.0036643066,
 -0.0040948438,
 -0.0015290236,
 -0.017673703,
 0.0067335996,
 -0.0060480847,
 -0.011052823,
 0.0021339152,
 0.0108906105,
 -0.017957833,
 0.010143996,
 -0.008718729,
 -0.013908783,
 -0.028953904,
 0.012732251,
 -0.002460909,
 0.00015944938,
 -0.0033448846,
 0.0020692188,
 -0.004117113,
 0.00081062777,
 -0.015370141,
 -0.022222035,
 0.0027975813,
 0.017276663,
 0.010796847,
 0.0021838224,
 0.008226018,
 -0.0025097427,
 0.0052061034,
 -0.00968991,
 -0.009118852,
 -0.00830774,
 0.0052812286,
 0.015576371,
 -0.0006726257,
 0.02950089,
 6.33185e-05,
 -0.00072660536,
 0.004060747,
 0.00441935,
 -0.0022906635,
 -0.0206535,
 -0.014716405,
 0.007246979,
 -0.007573268,
 0.0021338258,
 0.0029786553,
 0.015675863,
 -0.011832993,
 0.0055261594,
 -0.013414291,
 -0.0049424786,
 0.004292969,
 0.009572835,
 -0.011687416,
 -0.004751593,
 -0.018778224,
 0.0060855723,
 -0.0070855194,
 -0.0073878057,
 0.002895825,
 0.00023791163,
 0.0041022673,
 0.02055629,
 -0.0023087237,
 0.0039525577,
 0.01927094,
 -0.0030533536,
 0.029693417,
 -0.0042741834,
 0.0041762963,
 0.0019673964,
 0.00010093547,
 0.0146326935,
 -0.028787138,
 0.012454598,
 -0.016407084,
 0.017167127,
 -0.0029877683,
 0.006441368,
 0.0037990296,
 0.005800647,
 0.0038963296,
 -0.023051497,
 -0.0013374969,
 0.0015454009,
 -0.012214284,
 -0.0009545458,
 0.015501551,
 0.0030565131,
 -0.00068206247,
 -3.134659e-05,
 0.013967662,
 0.009155702,
 0.006735777,
 0.011899789,
 1.870792e-05,
 -0.009604598,
 0.0011024099,
 -0.0073571997,
 0.0014244973,
 0.0058007794,
 0.0014797319,
 -0.013264491,
 -0.025128381,
 -0.0018603178,
 -0.0011471817,
 0.0035695576,
 0.03161799,
 -0.00031971565,
 0.016533388,
 0.010331214,
 0.0058974354,
 0.009543357,
 -0.0028317852,
 0.004933537,
 0.016205996,
 -0.0022080205,
 0.0051760455,
 0.014585024,
 0.00095666695,
 0.0020298627,
 -0.00543682,
 0.02540815,
 -0.009943879,
 -0.0055097872,
 0.0035353857,
 -0.0063327816,
 0.0027832452,
 -0.005243538,
 0.0036849712,
 -0.002771523,
 0.0073145516,
 0.004619199,
 0.0088235475,
 0.00894073,
 0.011602996,
 -0.015821045,
 -0.016225656,
 0.0044643735,
 0.018414656,
 0.0106210485,
 -0.018088713,
 0.004092257,
 0.007479299,
 0.010134427,
 -0.0034597262,
 0.0026702096,
 -0.0061088116,
 -0.005381937,
 -0.004451152,
 -0.0070385467,
 0.022773549,
 -0.006426767,
 0.00038366413,
 0.003875424,
 0.00014751797,
 0.00898463,
 -0.0011750103,
 -0.012019319,
 -0.008827897,
 -0.003964525,
 0.0069222455,
 0.0036104394,
 -0.009610639,
 -0.015359965,
 0.005111597,
 -0.001322303,
 -0.0009909496,
 0.024071459,
 -0.003886326,
 0.008534433,
 -0.022998614,
 0.014515351,
 0.01869151,
 -0.016167028,
 0.023246536,
 -0.014213641,
 0.017314477,
 -0.0029975986,
 -0.004791104,
 -0.022587705,
 -0.009407915,
 -0.0059190746,
 0.0046905465,
 -0.008483433,
 -0.013811163,
 0.006631783,
 -0.010962695,
 0.010450236,
 0.015564505,
 0.011864795,
 -0.00193519,
 0.09630002,
 0.0134895835,
 0.006489781,
 0.0032524385,
 0.0034989892,
 0.015448505,
 -0.0025146734,
 -0.0076196333,
 0.016741438,
 0.014681803,
 -0.0025708368,
 -0.0021463034,
 -0.005581291,
 0.0033562751,
 0.0025257843,
 -0.00074673846,
 -0.009098228,
 0.0074077407,
 0.009588566,
 -0.009883919,
 -0.011108211,
 0.0062096394,
 -0.006719336,
 -0.0066164336,
 0.0003507483,
 0.00481594,
 0.0033618887,
 0.0046242382,
 0.002311532,
 0.0039534443,
 0.011497633,
 -0.009392616,
 ...]

#### Create Qdrant Collection

In [29]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [30]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-01",
    vectors_config=VectorParams(size=3072, distance=Distance.COSINE),
)

True

In [32]:
### Embed Data

pointstruct = PointStruct(
    id=0,
    vector=get_embeddings("Hello World"),
    payload={
        "text": "Hello World",
        "model": "gemini-embedding-001"
    }
)

In [34]:
pointstruct

PointStruct(id=0, vector=[-0.030313896, -0.0011937966, 0.011944085, -0.06331687, -0.018562978, 0.006006837, -0.013848489, -0.0069041, 0.018909177, 0.0067635323, -0.0013741076, -0.012544641, -0.012370406, 0.05024206, 0.14017393, -0.0023973074, -0.0021481998, -0.006960438, 0.008675419, -0.012715995, -0.001812732, 0.0038445718, 0.007866856, -0.018134868, -0.024915073, -0.012399078, 0.025578758, -0.002082866, 0.028287888, -0.003586746, 0.004083515, 0.015775781, -0.0004313633, 0.008374812, 0.008510412, 0.017772533, 0.02911796, 0.020505413, 0.00085054873, 0.027917791, -0.0065016323, -0.00055489736, 0.010354559, -0.014056266, 0.006188762, 0.01914849, 0.0056114774, -0.02003173, 0.009173776, 0.046414502, -0.028422333, 0.0009706299, 0.00034367744, -0.15495303, -0.03205103, 0.015597616, 0.0014483529, 0.013244147, -0.0012753017, -0.0069762473, -0.0065743234, 0.026333023, -0.033914164, -0.03351515, -0.014084813, -0.021122253, -0.0037559562, -0.015894454, -0.0132044535, 0.0009266045, -0.0046076463, 0.002836314, 0.010896628, 0.0055837515, 2.6554986e-05, -0.026512401, 0.029239267, 0.030210942, 0.022923402, 0.022045143, 0.0043289703, -0.006587189, -0.005106849, -0.016936187, 0.0049806694, -0.002627543, -0.04533331, -0.0077648, -0.023009295, -0.0013986771, 0.0062427456, 0.013982433, -0.00072732475, 0.017326867, -0.0063602338, -0.0066251936, -0.02029535, -0.012027261, -0.021167712, -0.016829435, -0.0039448985, -0.017997466, -0.019913562, -0.0033264023, 0.013208807, -0.006064849, 0.028672818, -0.02514688, -0.005154818, 0.018124957, -0.010284859, 0.013236621, -0.005510497, 0.0054104887, 0.024407003, -0.17566001, 0.0129672885, 0.033835325, 0.0051006298, -0.0067983717, 0.005552634, -0.0069785095, -0.007960976, 0.04508111, 0.020145552, 0.0013776658, 0.025661124, -0.0056492747, -0.005412729, 0.017054474, 0.0027260934, -0.013096773, 0.02703946, 0.0017097004, -0.0060478994, 0.00978527, -0.00038845162, 0.0012649546, -0.005448657, -0.0049788803, 0.008171673, 0.013693976, -0.0012799901, 0.0122965695, -0.006928518, -0.017596023, -0.02400427, 0.033872407, -0.0018897787, -0.004642682, -0.009462588, -0.0013214211, -0.01165622, -0.016433863, 0.017627925, -0.06062947, -0.016740393, -0.01028548, 0.026010621, -0.0053585866, -0.003944293, -0.019257408, 0.008068913, -0.010261724, 0.02781085, -0.016769039, -0.008422137, 0.00026563142, 0.020374864, 0.004697663, 0.0007952527, -0.008628621, -0.0071599293, 0.012253812, -0.009651952, -0.0068206824, 0.0020647887, 0.004918509, 0.004080372, 0.013318659, -0.0068530836, 0.012852206, 0.008347755, -0.005134643, 0.0019222737, -0.010027249, -0.03019924, -0.015115903, 0.022095283, -0.004943714, 0.012584554, 0.03965365, 0.008472304, 0.019622842, 0.0086460505, 0.017663684, 0.0021847396, -0.0061763404, 0.016309507, 0.0024802312, -0.005274451, 0.009630787, 0.027292749, -0.0042031733, 0.012754572, -0.0075161997, 0.0038046765, -0.01603709, 0.0029047756, 0.012737784, 0.01322164, -0.017942343, 0.024218237, -0.0025180918, 0.014748852, -0.003130954, 0.010107688, 0.0028677497, 0.010682057, -0.0032674903, 0.03283315, -0.016716631, -0.014839126, 0.017586727, -0.0054470683, 0.010866716, -0.03663272, 0.0068156705, 0.0016039904, 0.018086094, -0.00282021, 0.02585975, -0.0074394485, 0.003556373, 0.0039075343, -0.0063624317, 0.016064955, -0.0035883354, 0.004933564, -0.019253101, 0.007833977, -0.018342532, 0.022017917, 0.03234638, 0.025525102, -0.011283512, -0.02214131, 0.018973416, -0.014339129, -0.0059075127, -0.0075493855, 0.010773354, 0.014624269, -0.01585876, -0.0020889486, 0.0039724875, -0.010579039, 0.0013283786, 0.012698369, -0.003266931, -0.01388842, -0.01816451, -0.017868616, -0.024782885, 0.005581972, -0.008090774, 0.027093917, 0.014603971, -0.015107078, 0.016271638, 0.005475047, -0.008543388, 0.013230035, -0.03681613, -0.0061473423, 0.012686723, -0.092582695, 0.016451925, -0.013740081, 0.0068271076, 0.024917219, -0.01741403, -0.0114638815, -0.018869344, 0.0077150655, 0.020979477, 0.015177953, 0.010273044, 0.01963871, 0.003032966, -0.0039165965, 0.023959666, -0.004841975, -0.010688339, 0.021559618, -0.021349404, 0.03364167, -0.00023164171, -0.009174337, 0.0034483164, -0.0053871972, -0.02224095, -0.003824048, 0.041954275, 0.0023228202, 0.00021834475, 0.020529525, 0.02004328, -0.0041991826, -0.011219144, 0.02372387, 0.015473401, 0.006592454, 0.020301655, 0.022722557, 0.003597811, 0.019897025, -0.01847525, 0.010947462, 0.016650395, -0.0131313875, -0.00516318, 0.015278432, 0.013090853, -0.010892437, 0.020027872, -0.014198572, 0.008091364, 0.016337452, -0.022453519, -0.0010688595, 0.015870184, 0.022016348, -0.017563822, -0.013661122, -0.00026033938, 0.001518658, 0.004306147, -0.0007077401, 0.008010225, -0.011220006, 0.026747104, -0.0035587295, 0.0020554143, -0.0067774644, -0.00022558695, 0.0070354147, -0.008909337, 0.0052799494, -0.0010309784, -0.00045186735, 0.0022180695, 0.0022969316, 0.015824616, -0.03014863, 0.012357342, 0.01134582, 0.009171317, 0.015607439, 0.016570587, 0.026116002, -0.0041623926, -0.0056383912, -0.0057356283, 0.00618884, 0.0051885284, 0.028316813, -0.0035034865, 0.006614611, 0.011178137, 0.00057316636, 0.009211325, -0.0047507947, 0.008688266, -0.009272502, -0.0019169644, -0.03876579, 0.013807822, 0.017858714, -0.004087618, 0.0062047504, 0.008666273, -0.0032149088, -0.012709473, -0.008354743, -0.0012364847, 0.014541764, 0.011762554, -0.00056899927, -0.0012102567, -0.00016795206, 0.019294836, -0.013684108, 0.022067294, -0.008751329, -0.009392504, 0.0008341854, -0.018166337, 0.0059706923, -0.0008814969, -0.007001663, -0.00408203, -0.025787745, -0.014946882, 0.004066051, 0.0005709406, -0.0015279264, 0.0078978995, 0.020705521, 0.015040732, -0.01906574, 0.0077299704, 0.010964899, -0.0013570399, 0.019971384, -0.0035103124, -0.008846323, -0.010281885, -0.0013588223, -0.012409235, -0.015395761, 0.028040439, -0.010088732, 0.0052011996, -0.0077664973, -0.0509581, -0.011225459, 0.0050638635, 0.019561667, -0.012300919, 0.004331824, -0.029791297, 0.00854572, -0.021776069, 0.007175908, -0.008910408, -0.0006704371, 0.017720064, 0.0013713524, -0.01072456, 0.015046524, 0.019982914, -0.004373888, 0.025772022, 0.01669874, 0.016721023, -0.0013211521, 0.0053774626, -0.03698238, 0.0075974506, 0.0048729912, -0.003188799, 0.005501499, -0.0066846, 0.034861695, -0.0026045542, -0.028377185, -0.0095413765, 0.008044075, -0.022167474, -0.0016136164, -0.008271392, -0.012262523, -0.013889075, -0.012964201, 0.0013099437, 0.0019628075, -0.015295877, -0.0013176712, 0.0011235045, -0.013745, 0.023762783, 0.0039450647, -0.0110427905, 0.0026569196, 0.02650476, -0.017365016, 0.005922539, 0.020950519, -0.0152771, 0.012875862, -0.018262284, 0.013304323, 0.0023170079, 0.014832948, -0.009928457, -0.00056497037, -0.007111789, -0.022426993, 0.020926151, 0.031661507, 0.02360869, -0.009624175, 0.020925479, -0.0065130247, -0.017460277, 0.0069999825, -0.013113314, -0.0061913626, -0.005660234, 0.022048652, 0.03763691, -0.0038475953, -0.0026202172, -0.02530245, 0.015061175, 0.020261593, -0.0067861667, -0.017731633, -0.012365319, 0.014086816, -0.00822038, 0.00280056, 0.009888444, -0.013147878, 0.033857502, -0.033018384, 0.036588557, 0.011019051, 0.016823398, 0.0036695332, 0.004884206, 0.007071758, -0.0056496807, -0.005333046, 0.012366478, 0.02321422, 0.012080513, 0.03245054, -0.029629253, -0.015995376, 0.023977764, -0.007912966, -0.0018980596, -0.006954912, 0.021356631, 0.004142093, 0.026875203, 0.020461045, 0.003529857, -0.027063409, 0.0063684895, -0.020345999, -0.02751167, 0.0137914345, -0.1409646, 0.020562014, -0.012165011, -0.003497248, -0.0075151557, -0.03643196, 0.011128401, 0.0016969054, -0.022637665, 0.0011308519, 0.023390478, -0.008761264, -0.020568103, 0.012501698, -0.0017513502, 0.009198846, -0.001274773, 0.020714685, 0.019397885, -0.026851196, -0.011693651, 0.015566963, 0.0069672004, 0.0011245587, -0.020654121, -0.0061780266, 0.033184975, 0.047336332, -0.011135213, -0.0019130907, -0.0072050123, -0.021083366, 0.0037343358, 0.009833785, -0.0008500997, -0.0018181234, -0.008884832, -0.009826564, 0.0032127663, 0.021710787, 0.012904722, 0.013534631, 0.0051217973, 0.0100915115, -0.010530831, 0.008464727, 0.017200748, -0.023796916, -0.012799003, -0.018812642, -0.025634285, 0.022417214, 0.012988945, 0.009116467, -0.005357485, -0.010337424, -0.018941507, 0.010162669, -0.0130238775, -0.00058392715, -0.015361283, 0.021217832, 0.0132757, 0.022540126, -0.027666487, -0.0068040495, 0.007017373, 0.003258198, -2.4979572e-05, -0.0050840913, 0.0031126374, -0.005278033, -0.008710747, 0.018802045, -0.014362994, 0.0340723, -0.0074566794, 0.019522542, -0.012681242, -0.011851342, -0.024022048, -0.009165625, -0.08077808, -0.018588817, -0.007984595, 0.014864808, 0.010264386, 0.0018900833, -0.030959608, 0.0013177036, 0.0027529972, 0.005627166, 0.00020004636, -0.00052289636, 0.019142045, -0.028093783, -0.006210451, 0.023570158, -0.013570412, -0.0064797928, 0.006127547, -0.00023034478, -0.0066791466, -0.00076156575, -0.0085997, -0.018671114, 0.015895084, 0.03562971, -0.024336178, 0.011766951, -0.022796515, -0.024431624, -0.0054652547, -0.13559926, -0.007067103, -0.0022453857, 0.03150453, 0.030070646, -0.0049023805, -0.017810564, 0.03297769, 0.004904886, -0.02577335, -0.019053614, -0.017094664, -0.031843655, -0.009276262, 0.006134064, 0.12251774, -0.011233668, 0.012791833, -0.035270568, 0.00039501378, -0.005791186, 0.004648324, 0.010347055, -0.0020910176, 0.010537114, 0.021840453, 0.02154904, -0.030131992, -0.031007776, 0.018642198, 0.0063250265, -0.008175244, 0.007281372, 0.0027624331, 0.0089980215, 0.00021375243, -0.012315303, -0.026926983, 0.019079445, 0.004581479, 0.0032451898, -0.00072080665, 0.0006913845, 0.018346334, 0.0034571043, 0.006046893, -0.019315552, -0.013838123, -0.0009357324, 0.015031614, -0.0044954787, -0.06870273, 0.014274439, 0.017602418, 0.030042505, 0.025089532, -0.0137614915, -0.003422878, -0.010541789, 0.010796154, -0.009050845, -0.01184413, -0.010385283, 0.012336593, 0.0013547832, 0.016625205, 0.008959534, 0.009483302, -0.011422843, -0.00057953305, 0.0055535985, -0.0013027664, 0.014936357, -0.016341085, -0.018127227, -0.0018400219, 0.00027530655, 0.019652085, -0.0018642877, 0.007947813, -0.014752832, -0.019717084, 0.0057443357, 0.01643617, 0.015259061, 0.009167774, 0.001935739, 0.0075415466, 0.008288199, -0.002275506, 0.017029662, 0.004138769, 0.012517625, -0.022430768, -0.019255212, -0.011304842, 0.009630973, 0.0074840332, -0.008993811, -0.022280693, 0.019140478, -0.021848671, 0.022469116, -0.03638886, -0.007763379, 0.0050536175, 0.0032990735, 0.015837582, 0.02269879, 0.0041742683, -0.009448185, -0.0054117735, -0.0037365607, 0.0060009784, 0.009218504, -0.0008357219, -0.0034206447, 0.0063235336, 0.003261035, -0.015527293, 0.0015319582, -0.014543674, -0.015179417, -0.0005275774, 0.004096029, -0.013011487, 0.005232331, -0.006891182, -0.013670247, -0.027918959, 0.0138392495, -0.0010058744, -0.014489821, 0.008630248, -0.025206918, -0.002276612, 0.014981569, -0.0183151, -0.01138989, -0.013331324, 0.014140445, -0.0015370717, -0.012600631, -0.0027888436, -0.005979837, 0.0151958475, -0.008110423, -0.003409312, -0.0036036384, -0.0067948806, 0.019904274, 0.008026442, 0.016282188, 0.006594079, 0.006179156, 0.0012237764, 0.006888582, -0.007875747, -0.018095082, -0.022644525, 0.008470024, 0.008805389, 0.0070301867, -0.0021096529, 0.01708961, 0.018616993, 0.012102751, -0.017227225, 0.0046605715, 0.0015714809, 0.00029622047, -0.0058104894, -0.018940412, -0.011594058, 0.00015772098, 0.0012192485, -0.0011723682, -0.0072680605, -0.01070857, 0.013940822, 0.013954478, -0.0019129625, -0.0033290754, 0.010535496, 0.0031239102, 0.029862296, -0.005477032, 0.0039693005, 0.01154815, -0.006773816, 0.0025513151, -0.015714778, 0.01214634, -0.014207403, 0.014399074, -0.011962692, -0.0055507324, -0.0055467025, -0.005312243, 0.016891906, 0.008832677, -0.009232103, 0.0093835965, -0.00032623415, 9.528903e-05, 0.013213106, 0.0060440204, -0.0023045084, -0.013658106, 0.00601835, -0.002753023, -0.0055178897, 0.002396663, 0.0033798753, -0.0006745842, 0.0029888852, -0.0034899511, 0.00056369713, 0.004177558, -0.0014685111, -0.019111795, -0.020950198, 0.007970222, 0.0013478328, -0.0051277764, 0.00871483, 0.004090562, 0.012277771, 0.014780651, -0.004916014, 0.014002383, -0.0010904561, -0.00076050026, 0.0012152607, -0.0005874303, 0.009360158, 0.012169201, -0.0070881867, -0.003505732, 0.0014866317, 0.0124471905, -0.018587278, -0.01196502, -0.007593028, 0.007795659, 0.00302493, 0.0068332586, -0.010064607, -0.004822872, 0.007167714, 0.0012170364, 0.01621889, 0.018727196, 0.0032953173, -0.0050689885, -0.0038863544, 0.009786393, 0.0111545995, 0.002897237, -0.017303577, 0.0071921404, 0.007348203, -0.006965915, -0.0024107713, 0.015489584, -0.0008105035, -0.0017015579, -0.008436218, -0.009899542, 0.021519454, -0.010747908, 0.014259837, 0.0078011937, 0.0031258387, 0.0060834307, -0.007493037, 0.0034083237, 0.0092313355, -0.004098085, -0.005125598, 0.00020220125, -0.01078295, -0.013762541, 0.006639681, -0.008660636, 0.0025596502, 0.020292621, 0.000431504, 0.007885258, -0.022709887, 0.0067463424, 0.00788582, -0.002458208, 0.013774642, -0.009157685, 0.013004489, -0.015266235, -0.0015303994, -0.030372132, -0.0056738853, -0.014124911, -0.008441036, -0.0044700895, -0.02341307, 0.028257666, -0.0026603693, 0.005553896, 0.0077426303, 0.014410752, 0.0010929896, 0.1003517, 0.009153727, 0.010794766, 0.00096778735, 0.0039367545, 0.016191361, -0.00037745532, -0.0203021, 0.0022181934, 0.012946033, -0.012312165, -0.0047202366, -0.0012991303, -0.008072652, -0.017781947, 0.0148622785, -0.009600542, 0.0029447307, 0.006838907, -0.0037518982, 0.0011861069, -0.005434214, -0.0021441677, -0.004843135, 0.019197946, 0.0037314603, -0.005035116, 0.00091669237, -0.004570291, 0.007562835, 0.004775445, -0.00043601092, 0.0015872745, 0.01696961, -0.01918337, -0.0048826365, 9.136998e-05, -8.82107e-05, -0.0045306254, 0.004959254, -0.005732249, 0.003840157, -0.0094804615, -0.00094140926, 0.0012182969, 0.024464214, 0.006107546, -0.0048062066, -0.009165334, -0.013805578, -0.006484757, 0.009861726, -0.0038380008, -0.00968346, -0.016978864, -0.001369288, -0.0031768654, 0.002434471, -0.0032629396, -0.011853572, -0.008501315, 0.0065570557, -0.0032938763, -0.013719553, -0.0056354767, -0.025027094, 0.009052399, -0.009989258, -0.010530182, -0.009541539, 0.004805782, 1.89294e-05, 0.001614246, 0.005707338, 0.032487247, -0.007714544, -0.017076995, 0.0017170323, -0.0035218631, -0.011236558, -0.013199737, 0.011217662, -0.020442637, 0.0049554403, 0.005055403, -0.011947259, -0.024162358, 0.01023233, 0.01715725, 0.0043442273, 0.012780929, -0.009405914, -0.0072344616, 0.008616365, -0.014226685, 0.019278195, 0.09594784, -0.0008178701, 0.020151297, -0.0033929697, 0.0005612251, -0.004076405, 0.007763963, 0.01526745, 0.032607984, 0.002397361, 0.009561225, -0.009445524, 0.002920644, 0.002546943, -0.006229171, 0.009276351, 0.013703097, -0.009980723, 0.0057075312, -0.008866154, 0.0003313594, 0.008510134, -0.0073555317, 0.016481685, 0.011452784, -0.012540793, -0.008470392, 0.0026266244, -0.006485449, -0.007994941, 0.00348618, 0.004693819, 0.012602719, 0.0019801573, -0.0026347074, -0.009122949, 0.0010726115, -0.0013217907, 0.012081401, -0.0033365595, -0.0012987603, -0.0041881925, 0.006883778, 0.0066285282, -0.017690526, -0.01044949, -0.0048034177, 0.0040201293, -0.001636716, 0.017117755, -0.005640768, 0.003293303, 0.012716007, 0.003308691, -0.014571709, -0.011276153, 0.0035136554, 0.020836623, 0.018176137, 0.00019313666, 0.0019886787, 0.016802626, -0.006096618, 0.018712316, 0.0030634797, 0.012820069, -0.0040037925, -0.0022385418, -0.0006608862, -0.0031745199, 0.0017060204, 0.013083147, -0.016240701, 0.012196448, -0.003179665, -0.008525786, -0.0052757915, 0.005042163, -0.0026560563, 0.00619209, 0.010721847, -0.019373214, 0.0020842275, 0.009302038, 0.0029134247, 0.004868556, 0.009130905, -0.018466298, 0.00021816086, -0.015741542, 0.007793123, -0.00029677871, 0.012708148, -0.018112166, 0.004983914, 0.005103857, 0.00722482, 0.0014703011, 0.0008701071, 0.005824801, -0.009863618, -0.0031741383, 0.021474693, 0.0013430533, 0.0031240622, 0.004576053, 0.0078019663, -0.01096629, -0.0005532841, -0.0054400377, 0.0076332097, -0.009807329, 0.010802646, -0.004290145, -0.012702557, -0.0040174057, 0.019583683, -0.007522175, 0.00025436617, -0.0077302717, -0.011823012, 0.0013160475, -0.01538055, -0.010683908, -0.010513582, -0.00911192, 0.006736309, -0.0100164255, 0.010480771, 0.0046652015, -0.016446056, 0.018291628, -0.0033512034, 0.0021460038, 0.0011790388, 0.006787638, -0.021728717, 0.013532765, -0.009865805, -0.0144374445, 0.0016232508, 0.010216054, -0.00689371, -0.0010894046, -0.00058094645, -0.002643949, 0.004004028, -0.010371293, 0.015175857, -0.010929935, -0.013188104, 0.008488385, -0.00039205252, -0.009703082, -0.0008165175, 0.011180015, 0.010103562, 0.013386566, 0.009951477, 0.00015031519, -0.0045446814, -0.062483124, 0.0102612665, 0.009853922, 0.0075842827, 0.015632883, 0.00778497, 0.0027821297, -0.0053513297, -0.008674758, -0.003852737, 0.0026045386, 0.010278405, 0.00554796, 0.024155723, -0.011243839, 0.005260361, 0.008553121, -0.0013599639, -0.00061459024, -0.004847195, -0.013435701, 0.0009115604, 0.009218705, 0.018852277, 0.016659098, -0.007975623, 0.013697092, 0.01685826, 0.0022560975, -0.0033346217, -0.0024827558, 0.00037510763, -0.0045283334, 0.003953635, -0.001100526, -0.0006925117, -0.012148369, -0.009584042, -0.010240659, -0.014654325, 0.0030067968, 0.0090716425, -0.00040098623, -0.010951922, -0.007128352, -0.016578399, -0.01045762, -0.0029707581, 0.013503424, -0.0067613907, -0.003325714, 0.002518228, -0.023903335, 0.004348237, 0.0012129083, -0.010649385, 0.010860739, -0.0014278042, 0.0011327071, -0.0019291423, 0.019384235, 0.016564097, -0.010389986, 0.0069681783, 0.017860157, 0.00800328, 0.017344035, 0.005285293, -0.003610008, 0.0015001438, 0.004719489, -0.0027298515, 0.0027204938, -0.016247883, 0.00077357696, 0.0070947097, 0.011373355, 0.013336388, 0.013734648, -0.009696549, 0.004252123, 0.010456565, 0.003856687, -0.010859643, -0.0024370814, 0.00589248, -0.018256322, -0.012050936, 0.0029656172, 0.011210581, -0.009915172, 0.004990058, 0.022577528, -0.0025760368, -0.0026910903, -0.0035097844, -0.0032413057, 0.0065765423, 0.011399035, 0.015369315, -0.0026382252, -0.020708175, 0.0076527297, 0.013723686, -0.010769359, 0.009370336, -0.022521928, 0.008591228, -0.0043024677, 0.011832237, -0.0040613087, 0.0047961697, -0.00419849, -0.0011360069, 0.009858819, -0.004376024, 0.009846541, -0.0020979908, 0.005540551, 0.0034577304, -0.006568742, -0.0044444194, -0.003984797, -0.017097859, 0.007925138, 0.0015005147, -0.0029145635, 0.0227625, 0.012422622, -0.006393633, -0.0065999534, 0.0035142382, 0.016353752, 0.007240522, 0.002024224, 0.010372048, 0.010408531, -0.006935567, 0.0063993055, -0.006414042, 0.014774706, -0.01406865, -0.00030581182, -0.004311141, -0.0002228219, 0.0001306631, 0.017755374, 0.004197567, -0.002672011, 0.008106232, 0.002857935, 0.016495781, -0.01224831, 0.020954395, 0.012741935, -0.008753071, 0.011283346, -0.0026809124, -0.0065937038, -0.016455796, 0.015408036, -0.0069243703, -0.009329665, 0.0011192182, 0.0065758186, -0.008337713, -0.0034469005, -0.012771877, -0.004527032, -0.009992424, 0.005121942, 0.0028132387, -0.0014444636, 0.012951325, 0.009010905, -0.0026686701, 0.009831697, -0.0041870847, -0.01144455, 0.0034869572, -0.00027347248, 0.018274982, -0.0035455618, 0.009853527, 0.007898129, 0.0023406674, 0.0039324737, 0.00077211455, 0.009985556, 0.00839203, 0.005704424, -0.0044736946, 0.002603132, -0.016668478, 0.0057220133, 0.008595204, 0.007910733, 0.012318109, 0.010677215, 0.0046411483, -0.016260281, 0.002534653, 0.014120323, 0.013697502, 0.012069075, -0.10365203, 0.002509335, -0.007925616, 0.016748346, -0.004813268, 0.01248351, -0.010580489, 0.012396853, -0.00016119154, 0.003843562, -0.013520748, -0.009746544, -0.008428298, -0.04261646, 0.0006692387, -0.002469608, 0.0025722485, 0.009168042, -0.008860439, -0.008356979, -0.020064075, 0.015598731, 0.011718527, 0.004

### Amazon Data

In [35]:
len(data_to_embed)

50

In [36]:
pointstructs=[]
for i, data in enumerate(data_to_embed):
    embedding = get_embeddings(data["preprocessed_description"])
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embedding,
            payload=data
        )
    )

In [37]:
pointstructs

[PointStruct(id=0, vector=[-0.010977576, -0.008538937, 0.004236455, -0.07589605, -0.0014879254, 0.0053786193, 0.005274366, 0.008663739, 0.009658452, 0.004588908, 0.0051917583, -0.014114624, -0.03356956, 0.019495793, 0.11103883, -0.0090452675, -0.0020489923, 0.005078651, 0.0126835825, 0.009409637, -0.023331175, -0.010531944, 0.0142383715, -0.021991448, -0.01286905, -0.0106603755, 0.023119094, 0.020531483, 0.039112955, -0.0022672636, 0.00088329794, 0.022663286, 0.0046168887, 0.008672598, -0.00349664, -0.0077687493, 0.017381888, 0.019098476, 0.008272457, 0.024488414, -0.0024776082, -0.015764402, 0.0025611836, 0.013940097, 0.016249174, 0.009614298, -0.006651214, -0.026154011, 0.029669905, 0.03881756, -0.0025897012, 0.008393907, 0.020003777, -0.1632329, 0.009418588, -0.0028868266, -0.014461994, -7.6997596e-05, 0.008279342, -0.0023833527, -0.02737789, 0.035969835, 0.008231631, -0.015232494, -0.020477835, -0.04626063, -0.01682074, -0.0111779645, -0.020411115, -0.0155845275, -0.0063450383, -0.0037756965, -0.0008433352, 0.013121737, -0.0026721794, -0.03974941, 0.022038873, 0.0060554803, 0.008474262, 0.0017506706, 0.008176109, -0.0022749088, -0.008672082, -0.0033351702, 0.00870106, 0.0015474281, -0.022584662, 0.014325824, -0.030303419, -0.007950218, 0.0050624493, 0.01769067, 0.0038974667, 0.03238415, -0.016327722, -0.0037173384, -0.0112690795, -0.014679775, -0.019128557, 0.028926244, -0.02083034, -0.011245637, 1.9988393e-05, 0.0029433826, 0.008983193, 0.0048528435, -0.006404261, -0.022225328, -0.0063694157, 0.008879095, -0.0072864895, 0.017420098, -0.0007683548, 0.024423534, 0.008567363, -0.16382954, 0.014773987, -0.0025330551, -0.022874303, 0.007854415, -0.004281109, -0.0048554554, 0.0234387, 0.018206785, -0.00573633, 0.00042589204, 0.007307335, -0.018868193, -0.024498848, 0.018875135, 0.018006602, 0.008252229, 0.0033061095, 0.014083415, -0.008709973, 0.017073873, 0.015134857, -0.013171174, -0.0056552812, -0.007245486, 0.019344617, -0.0014490851, -0.028431399, -0.016520606, -0.014350214, -0.015099964, -0.0062617916, 0.033602092, 0.007061979, -0.019034974, 0.008627254, -0.013942712, -0.015792174, 0.021968333, 0.0035083857, -0.065997995, -0.010618274, -0.0010087945, 0.0154211335, -0.00025468905, -0.0005555449, -0.0058488217, -0.0023539772, 0.0016131861, 0.01524213, -0.028440455, 0.015979499, -0.0036275706, 0.035015352, 0.025044667, 0.00016999253, 0.0071343905, 0.010224188, 0.0208489, -0.0113516105, 0.0015864649, -0.0036546635, 0.004242764, -0.0030238938, 0.01605804, 0.01238347, -0.01123254, -0.0077403765, -0.0061267703, -0.0019728336, -0.01429339, -0.04935476, -0.040297695, 0.011204701, -0.0060468996, -0.0033222123, -0.0005502433, -0.01470085, -0.0068560615, -0.0035172103, 0.023594812, -0.017466169, 0.0027079352, 0.015668951, 0.011066471, 0.016612938, -0.021916911, 0.018441083, -0.0016264111, 0.023098642, 0.0077204322, 0.013603329, -0.012963863, 0.010167727, -0.0011598471, 0.023574384, -0.0077622626, 0.014000533, -0.014325021, 0.019268468, 0.020927994, -0.00960342, 0.00552572, -0.030492758, -0.014207785, 0.0074177994, 0.004988618, -0.008347187, 0.0026450465, 0.011886518, -0.014490683, -0.023050794, 0.016811438, -0.002011526, 0.012894215, -0.011654114, 0.02877881, 0.005227064, -0.030494193, -0.0033306559, 0.0013586067, 0.004493965, 0.024634833, 0.027441947, -0.008312707, 0.002179052, -0.0155983865, 0.013168727, 0.020617971, 0.018429248, -0.003822589, 0.004624686, 0.009718939, -0.024462562, -0.0014792418, -0.033787873, -0.019355986, 0.012792525, -0.019552033, -0.003999729, 0.016937166, -0.012634101, 0.012650292, 0.036124285, -0.008352897, -0.022229573, -0.008128516, 0.018089028, -0.020051256, 0.022323336, -0.0008931528, 0.015101985, 0.0033228856, -0.0071599134, 0.008767191, 0.0021121306, -0.010280202, 0.00043331005, -0.009707299, 0.001228729, 0.0039743995, -0.06731393, 0.011335709, 0.0052367197, 0.005355175, 0.02709473, -0.004212037, 0.004807891, -0.005902509, 0.0015259851, 0.0181173, -0.011658989, -0.029943645, 0.0171767, 0.00712087, 0.015930576, 0.02034999, -0.01063676, -0.017607052, 0.025443904, -0.04992722, 0.0036540104, -0.010127112, -0.02658641, 0.027297273, 0.010796827, -0.010580111, -0.007753833, 0.06491265, -0.0006233673, -0.0009746784, 0.0042324867, 0.0007462395, 0.008516371, -0.008991117, 0.012915111, 0.005643075, -0.0033110834, 0.01268038, 0.011338184, -0.0040437146, 0.007273115, 0.010996408, -0.014937338, 0.038356096, -0.015394305, -0.0008945153, -0.011404952, -0.009901436, -0.013553778, 0.01587104, -0.0018819879, -0.015455434, 0.006409243, -0.028013652, -0.0049721776, 0.0101245865, 0.005131103, -0.01999542, 0.0083368, 0.021389741, -0.0067881765, -0.021911882, 0.011218515, 0.0038539371, -0.014668115, 0.022694882, -0.03580594, -0.015700152, -0.024827983, 0.016045896, 0.001071151, 0.0047152154, 0.0022792795, -0.0053869477, 0.026214238, 0.013294341, 0.0017479376, 0.0053653372, -0.04267118, 0.02685469, -0.0025098007, -0.007885987, 0.017030554, -0.007505124, -0.0022087207, -0.003035347, 0.009516664, -0.006677297, 0.0022214411, -0.010801387, 0.025114374, 0.008670207, -0.00682233, 0.019946257, -0.013729065, 0.023306152, 0.007445115, 0.025599629, -0.0009007643, -0.011220048, -0.018694544, -0.0071487552, -0.006068043, 0.0048741084, -0.0025261778, 0.008211104, -0.014941308, -0.018509185, 0.002150444, 0.009108956, 0.0073377653, 0.0044118753, -0.025080426, -0.0039936746, -0.0033075197, 0.020275021, 0.002992181, -0.00441492, -0.013549298, 0.010451931, -0.002788871, 0.0051947227, 0.009519652, 0.00802531, 0.016046751, 4.6288606e-05, -0.021051727, 0.0007349951, 0.0095021445, 0.011407901, -0.019256126, 0.018365584, -0.028063009, 0.004509393, -0.01731145, -0.0171872, 0.013237079, -0.018688928, 0.0089604985, 0.015242928, -0.03930913, -0.015282583, 0.026747266, -0.009546028, 0.0010850332, 0.01939446, -0.0024317836, 0.04530009, -0.02862275, -0.02785455, -0.0160301, 0.00078078645, 0.002182515, -0.01528734, -0.0009121121, -0.011248195, -0.01529562, 0.025089214, 0.0073333397, 0.0017697588, -0.0047646035, 0.011723406, 0.013204002, -0.006014636, 0.02326092, 0.010259894, 0.016389752, 0.021220177, 0.008773496, 0.035888776, -0.020433038, 0.016931582, -0.011095856, 0.004780983, -0.021279352, 0.024002772, -0.0041333796, 0.007794688, 0.025385637, -0.007619647, -0.018174304, -0.0052710935, 0.021062776, 0.013084199, 0.004488886, -0.014436432, -0.011467563, -0.0038883404, -0.018182741, 0.0037803056, 0.0063520423, -0.02152022, 0.005564789, 0.005611667, -0.007998822, 0.02151653, 0.009444837, 0.021481633, 0.00362106, -0.0017350134, -0.020774718, 0.00038533873, 0.007333268, -0.006623127, -0.011957569, -0.021498889, -0.0030104208, 0.016827997, 0.030860879, 0.012945429, -0.004155358, 0.002525818, -0.013412846, 0.02192686, 0.01630232, -0.006225172, -0.019109497, 0.010019519, -0.025107771, -0.015117008, -0.020597419, -0.00015762335, 0.029788723, -0.005740921, 0.03504255, 0.009286612, 0.011151921, -0.01639778, -0.012259168, 0.001495705, 0.0124361925, -0.015331183, -0.014742643, -0.019544791, -0.012758027, -0.006716287, 0.017428216, 0.036498014, -0.0031905088, 0.037137065, -0.03181149, 0.012815027, 0.0024700365, 0.016704528, 0.0055888877, 0.019759497, -0.0024424607, -0.033981707, 0.013198289, 0.0076223435, 0.02421038, 0.0055437936, 0.022849241, 0.006399139, -0.02121349, 0.029889788, -0.0064850943, -0.010163254, 0.026718168, 0.004234622, 0.009686599, 0.023668176, 0.021064462, 0.023283094, 0.010876168, -0.008712941, 0.010875923, -0.012251853, -0.00011734268, -0.14989386, 0.0044667874, -0.0018074827, -0.01449782, -0.027572257, -0.0062969495, 0.00072505465, -0.011494623, 0.008502124, 0.028491478, 0.019324781, -0.015528833, -0.008388859, 0.023452174, 0.004324213, -0.0097833285, -0.015178853, 0.00076360896, -0.010465108, -0.014676871, -0.011130347, -0.0025852374, 0.005092712, 0.013608042, 0.016319118, 0.0017056115, 0.047605496, 0.03846045, -0.019056004, 0.011187349, -0.0082228845, -0.013712131, 0.0020564198, 0.02359766, -0.011085049, -0.013782882, 0.015772387, -0.01365745, -0.0113459295, 0.022648636, -0.010099804, 0.024235988, -0.010876393, -0.0138956, -0.023667695, 0.012943074, 0.023730902, -0.0049019502, 0.0046735387, -0.027399722, -0.019554336, 0.0006596826, 0.0059810155, 0.0116008045, -0.01998163, -0.022147685, -0.024000147, 0.028469425, -0.020958012, 0.005824255, 0.013420335, -0.0058549913, -0.015463738, 0.0073812613, -0.002421202, 0.0053747576, -0.02109835, 0.021479245, 0.013016668, 0.018245336, -0.007741415, 0.019292258, -0.00093773316, 0.016180277, -0.009963114, 0.009210774, -0.0058024423, 0.044826325, -0.0054132394, -0.0052400148, -0.026903152, 0.008181047, -0.09913115, -0.011960926, 0.0055599697, 0.028877275, 0.021509195, -0.01593064, -0.0111033525, 0.0052335165, -0.00013481778, 0.0056520198, 0.016379576, -0.00020050397, -0.0021874905, -0.023923622, 0.013536214, 0.011419467, -0.0014876436, -0.0008219125, 0.024573, -0.0034752565, 0.011460932, -0.0032305883, -0.005213868, -0.007623592, -0.015285739, 0.035088014, 0.011424609, 0.0017675693, 0.004102203, -0.029941892, 0.008471917, -0.14050514, -0.003094956, -0.03036119, 0.014076368, 0.022523815, -0.013482863, -0.026452612, -0.0032457607, -0.009578184, -0.008245708, -0.00820117, -0.030857313, -0.041310992, -0.012576014, 0.032712556, 0.1196694, -0.024586419, 0.003280202, -0.008916518, -0.0111906985, -0.0062247724, -0.028320745, -0.008024483, -0.015521145, 0.019669158, 0.005921669, 0.028054357, -0.0059876493, -0.0036363017, 0.004516082, -0.0017344379, 0.008403061, 0.00048732676, 0.013528533, 0.0027820983, 0.013942875, 0.0112760505, 0.00064554624, 0.009843215, -0.009882693, -0.015799748, 0.034850553, 0.012240533, 0.01113686, -0.0075541125, -0.013118138, -0.020517757, 0.0031798037, 0.00078969734, -0.012111305, -0.0353598, -0.067233875, -0.0013283655, 0.031518176, 0.012593116, 0.01624949, -0.0101118535, 0.019465871, 0.0023902813, 0.020294761, -0.004267558, 0.0093192, -0.008980263, 0.01694396, -0.028601935, -0.0015218984, 0.0018286636, 0.022941299, 0.004742123, -0.0091122715, 0.0065754456, 0.02083389, -0.00029809822, 0.017080072, -0.005322228, -0.011482393, -0.0053700465, -0.004699709, -0.020146953, 0.0038356846, 0.0014348531, 0.0064914813, 0.016255844, -0.013885871, -0.00033529554, -0.012694749, -0.013099181, 0.010935269, 0.020077925, -0.007043308, -0.0012063507, 0.032243084, -0.009359944, -0.018260082, -0.015512845, 0.0023295667, -0.011235413, 0.009964755, 0.009128984, -0.0055738115, -0.012974866, -0.02630174, 0.02242842, -0.03342933, -0.008401036, -0.014624003, 0.01134578, -0.0025730657, 0.017966714, -0.004529815, 0.0055625015, -0.0027862003, -0.007381891, 0.005578773, 0.007850132, 0.0024710007, 0.0067940955, -0.0012603455, -0.0025415835, -0.009103943, 0.013254858, -0.021132857, -0.017472604, -0.007914156, -0.00031076587, -0.0033437177, -0.004292962, -0.013340287, -0.0057132225, -0.035862494, 0.010432207, 0.0032679748, -0.005394343, -0.012591963, -0.0025939455, -0.0023683351, 0.007915425, -0.0033410932, -0.0026470092, -0.002893399, 0.018882416, 0.0170943, -0.00030692978, -0.0016643261, 0.0049173404, 0.006504258, -0.010250203, 0.007817702, -0.023224784, 0.006130944, 0.017173953, -0.009644979, 0.030410625, 0.0037506719, -0.00012561496, -0.002764168, -0.0064581763, 0.0013568258, -0.025915267, -0.0113681415, 0.008401385, 0.0072244895, 0.01432021, -0.0007983562, 0.008071814, 0.0018409959, 0.005488485, -0.014708981, -0.0036462846, 0.0053323214, 0.008009614, -0.0041157, -0.0037871862, -0.016571674, 0.0013277273, 0.0013926041, -0.0016570847, 0.00657886, 0.006976131, 0.0040813363, 0.015982816, -0.010154358, 0.0039267037, 0.004426385, 0.01457258, 0.017323555, -0.0011630642, -0.0031105164, 0.007472737, -0.00053200487, -0.00299275, -0.029142078, 0.024053764, -0.0044294386, 0.01621933, 0.016676757, 0.0006002344, 0.0022775284, -0.0072623966, 0.018095594, -0.008643488, -0.006755541, 0.00063372875, 0.0025629168, -0.0032901587, 0.011576033, 0.0016746743, -0.0009546543, -0.0148834055, 0.0068064756, 0.00126663, 0.0072214524, 0.0022135254, -0.00747267, 0.010320177, -0.00089665945, 0.0009338894, 0.0028586679, 0.011384585, -0.0015502612, -0.0070044445, -0.004873516, 0.010421271, -0.0034700965, -0.0170594, 0.01836495, -0.014502252, 0.016863022, 0.0044002444, -0.0049621235, -0.00781942, 0.0018881668, 0.00051551533, 0.004820392, 0.0007773589, -0.002946959, 0.018551864, -0.007943429, -0.011865535, -0.009632639, 0.0131450705, 0.0047684093, -0.015209765, -0.015013688, 0.008867031, 0.007951143, -0.0078469915, 0.0016996869, -0.0047466387, 0.0110948095, 0.010745959, 0.016019596, 0.018541453, 0.014530228, -0.0064143096, -0.01266983, 0.012437367, 0.01753424, -0.012611532, -0.021210494, 0.0039357045, 0.010587068, -0.0016121102, 0.008302526, 0.011759653, -0.0065638567, -0.009236775, 0.020814009, -0.01868737, 0.013089368, -0.0123336995, -0.007972769, -0.009728199, 0.008974303, 0.0019963481, -0.0059608277, -0.0035780198, 0.009211372, -0.009568457, 0.004769131, 0.011373759, -0.01270318, -0.015515689, -0.0031838329, -0.0023551253, 0.010574044, 0.013640843, -0.0098032495, -0.009438512, -0.011966477, 0.009928148, 0.014553035, -0.01218609, 0.012437551, -0.008266692, 0.019273596, 0.004399254, -0.0073371343, -0.018666875, -0.0038236685, 0.00042807285, 0.00411665, -0.002529971, -0.0038298026, 0.022143634, -0.01744882, -0.00010408957, -0.0047391555, 0.0143864425, 0.0116096735, 0.09577051, 0.017753504, -0.0012024617, 0.014054407, -0.0052764365, 0.0026428464, 0.0091168145, -0.011282751, 0.010021203, 0.0078115277, -0.026688801, -0.01060151, -0.0060961433, -0.00045831865, -0.002344976, -0.0012802597, -0.01359078, 0.010163359, 0.00803578, -0.0064963857, -0.011246877, 0.006602893, -0.0071317144, -0.012796844, -0.015109671, -0.008049874, 0.008652049, 0.0034701552, 0.005751126, 0.0070260875, 0.0015283637, -0.009808569, -0.002181358, 0.0114665935, -0.0056700655, 0.005094608, 0.0021613073, 0.006304586, 0.0027933558, 0.0016191438, 0.013822927, 0.008225866, 0.0089154085, -0.0016561799, -0.00024540818, 0.017486433, 0.0025946219, -0.013500096, -0.020628577, -0.008562787, 0.006479351, -0.011786153, 0.000866792, -0.0009472666, -0.029442357, 0.0034125247, 0.0048038587, 0.009378465, 0.0005879125, -0.024590027, -0.0149758225, 0.018447917, 0.007563932, 0.0029238383, -0.009032473, -0.023554267, 0.014386166, -0.010127385, -0.011627002, -0.0042875987, -0.0038180489, -0.004298091, -0.00456448, -0.0055960477, 0.038651854, 0.0036532045, -0.013347922, -0.0135994125, -0.015288762, 0.003798921, -0.008714946, 0.010715062, -0.01634486, -0.009853536, 0.002969886, 0.0055439486, -0.010672965, -0.0021655152, 0.027493926, 0.0027719236, 0.011979798, -0.018300222, 0.009339844, 0.020016612, -0.0018143044, 0.0061033396, 0.09293446, 0.006449641, 0.015524031, -0.001110623, 0.0048914566, -0.023576535, 0.0009252406, -0.008477787, 0.0152949635, -0.0016595557, 0.01206078, 0.010500641, -2.6481495e-05, -0.0077537876, 0.0068808654, 0.0009166311, 0.017917497, -0.0014051193, -0.0033112173, 0.0025933266, -0.003128647, 0.01653778, -0.009896851, 0.0008391126, 0.0049899663, -0.012672854, -0.012629127, -0.005143735, -0.0042348322, -0.009154581, 0.0008436756, 0.0019942976, 0.0068286783, 0.0091970125, 0.00068948587, -0.0029536774, -0.0024196121, -0.009765295, 0.0020556226, 0.0058243773, -0.004044497, 0.0039574457, 0.00093480985, 0.008217501, -0.005586793, -0.008817079, -0.010809742, -0.008475019, 0.0010368155, 0.013130407, -0.0032670433, 0.00058593054, -0.0029246174, 0.018005606, -0.008950027, -0.0040894337, -0.011485949, 0.011248717, 0.001614093, -0.004711036, 0.008141721, 0.013626552, -0.0025707108, 0.015003776, -0.008035553, 0.014444324, -0.015309306, -0.0022059986, 0.008212564, -0.01847039, -0.005778884, -0.004426064, -0.0048476495, 0.003579018, -0.022261396, 0.006745569, 0.0025087723, 0.011987427, -0.010650198, 0.0026199915, -0.0012217553, -0.01849917, 0.008417588, -6.987471e-05, -0.00555198, 0.0018037943, 0.0011441256, -0.0036604444, -0.019350195, -0.0057641026, 0.0067777336, -0.0086053135, 0.021065183, -0.018105334, 0.0034626038, -0.0013684192, 0.0026220898, -0.0071007684, 0.010099542, 0.003909418, 0.012480654, -0.00069431285, 0.026285589, 0.0025451016, 0.018200254, -0.0010217393, 0.00020924643, -0.019078568, 0.008909354, -0.00016745142, 0.01031135, -0.0065292874, -0.0019038239, -0.010424899, -0.0083629, -0.020205619, -0.0035300446, -0.017325426, 0.005230772, -0.011885847, 0.0044933828, 0.004167361, 0.003310577, -0.0023080553, -0.0058057792, 0.007160749, 0.0014430602, 0.008598646, 0.013317463, -0.0068007535, -0.007078704, 0.007110902, -0.0022954796, -0.017585374, 0.006292457, 0.012232303, -0.011555416, -0.004894044, -0.008521856, -0.018643977, -0.012510417, 0.01286881, -0.017300813, 0.0012654546, 0.0055513345, 0.01604126, -0.0069877957, -0.002740751, 0.01025518, -0.009617959, -0.01287759, 0.01059482, -0.015959809, -0.0046511167, -0.0097168125, -0.001740243, -0.0006366659, 0.019290796, -0.004410358, 0.0039489972, 0.000105265906, -0.051748667, 0.012476675, 0.012845485, 0.0024134177, -0.0007680552, 0.0046666954, 0.0028161681, -0.002276535, -0.01033624, -0.0017100851, 0.00020308846, -0.003785896, 0.005317862, 0.011074119, 0.0028202715, 0.019230392, 0.0049567483, -0.0032286665, -0.0065170336, -0.00021091447, -0.012914034, 0.0118699, -0.0068679336, 0.01619789, 0.0039215786, -0.0025897773, 0.006962876, 0.008275146, -0.0077039558, -0.0045066457, 0.0038215485, 0.0036059574, -0.0018175072, 0.015085708, -0.0072075534, -0.0017514636, -0.00549555, -0.015302758, -0.011833321, -0.011161382, 0.009831278, 0.0033287955, -0.0069463537, 0.008832935, -0.007024907, 0.0022018126, -0.00029844962, 0.005538712, -0.007299161, 0.0004892098, -0.0005320889, 0.018932432, -0.012279921, 0.005278509, 0.007588963, -0.0072374344, 0.021999115, 0.0010845122, -0.0030738697, -0.00024565434, 0.0056224167, -0.0025152117, -0.021240158, 0.008332689, -0.014915258, -0.0045260796, 0.004715385, -0.00018194526, -0.014461538, 0.006163931, 0.0045379945, 0.004174535, 0.0038025968, -0.0017189623, 0.0046554906, 0.0049372367, 0.021217272, 0.010802065, 0.008663275, -0.0017922437, 0.006019865, 0.0062679388, 0.009901362, -0.012632474, 0.009498048, 0.006377453, -0.0044101113, -0.002041346, 0.0061334665, 0.0021029674, 0.011681913, 0.0070487675, 0.007832694, 0.004220313, -0.004240027, 0.00530122, -0.019904632, 0.0015101297, 0.0028004246, -0.0042267176, 0.0052161105, -0.009786064, -0.0107238665, 0.007897304, -0.015100699, 0.010029222, -0.01077785, -0.00998005, 0.0075207413, -0.0060807243, -0.0012916526, 0.0051586907, -0.0025570118, 0.006087602, -0.018304024, -0.008076784, -0.0019228056, 0.008556756, 0.0008439812, 0.001629777, 0.006431181, 0.014328717, -0.0009753187, -0.00060348894, -0.0020920886, 0.013173117, -0.0016435061, 0.0085789235, 0.0029382936, -0.015933461, -0.003028847, 0.008034874, 0.0016893648, 0.008042642, 0.009156718, 0.008468294, 0.012392527, 0.011530458, 0.007665595, 0.0029610659, -0.00236464, -0.005632978, 0.02056164, -0.008820968, -0.010794565, 0.015926335, 0.0042383685, 0.010920411, -0.004084902, 0.006797695, 0.0060339016, 0.022016961, 0.0133462995, 0.013692396, -0.0008306168, 0.00479552, -0.011181734, -0.0154765835, -0.007598249, -0.014284329, 0.010682729, -0.015558034, -0.009062173, -0.0049777715, 0.0064870636, -0.00018792562, -0.008981901, -0.00035711125, -0.009113743, 0.0041701454, 0.005680205, 0.018487183, 0.002210723, 0.011062174, 0.009824051, 0.0046147467, 0.015256792, -0.0001578287, -0.021881737, -0.01664146, 0.006236927, 0.005873498, 0.0059515755, 0.006994653, 0.014979047, -0.003527241, 0.01221198, -0.0038789012, 0.016844464, 0.0036903878, -0.0007839398, -0.0140361795, -0.014954119, -0.01902473, 0.01591985, 0.0024213088, 0.01642758, 0.004186427, 0.0021691397, 0.0043635163, -0.008757048, -0.002282119, 0.010882736, 0.015780777, 0.0001844285, -0.097846255, -0.01570669, 0.0022570754, 0.01138298, -0.00747076, 0.0062109404, -0.0061984337, 0.0044262493, -0.011561166, 0.004137509, 0.0081310775, -0.011270428, -0.011659075, -0.022433428, -0.0031159762, -0.0070748194, 0.006740887, -0.011719379, -0.0077950726, -0.0009743299, -0.00032408722, 0.017364671,

In [38]:
len(pointstructs)

50

In [39]:
### Write embedded data to Qdrant

qdrant_client.upsert(
    collection_name="Amazon-items-collection-01",
    points=pointstructs
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

### Define a function for data retrieval

In [40]:
def retrieve_data(query, k=5):
    query_embedding = get_embeddings(query)
    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01",
        query=query_embedding,
        limit=k
    )
    return results

In [42]:
retrieve_data("do you have any smart watches?").points

[ScoredPoint(id=5, version=1, score=0.79831743, payload={'preprocessed_description': "Smart Watch, Tykoit Smartwatch 41mm with Heart Rate Monitor & Sleep Tracking & SpO2, IP68 Waterproof Fitness Tracker with Step/Calorie Counter Compatible with Android and iOS Phones Heart Rate, Sleep and SpO2 Monitor: This smart watch built in high performance motion sensor automatically detects your heart rate in real time, and also measure your SpO2 and deep, light sleep state which can help you better understand your health. (NOTE: the data cannot be used as a medical-grade test) All-day Activity Tracking: This smartwatch has 8 kinds of sports modes (walking, running, treadmill, bicycle, yoga and other workouts). The fitness tracker display shows your accurate steps, distance, calories, active minutes and you can also see more detailed data on App. Customizable Watch Face: Our smartwatches support customizable watch faces with your favorite pictures to suit your daily mood and occasion. And the fitness watch with 1.4 inch color full touchscreen display for exceptional hd quality, making it easy and quick to view time and date. Smart Notifications and More Practical Features: All messages and notifications will show on your wrist and remind you through vibration. It cannot answer call or text on sports watch. There are also many convenient functions like Timer, Stopwatch, Wake-up Gesture, Find Phone, Sedentary Reminder and Music Control. Long-lasting Battery Life & IP68 Waterproof: The smartwatches could last about 10 days when in auto monitoring mode for heart rate or 7 days when in the instant detection mode. Our active watch is designed with IP68 waterproof standards, protect yourself against sweating, rainning, and other water splashes. Also can wear it without worries while swimming(Please note: This device can't track your swimming data).", 'image_url': 'https://m.media-amazon.com/images/I/41fLyn2USrL._AC_.jpg', 'rating_number': 299, 'price': None, 'average_rating': 4.1, 'parent_asin': 'B09SNWJC5N'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=30, version=1, score=0.7829777, payload={'preprocessed_description': "Military Smart Watch Men(Answer/Make Calls), 2023 Newest Outdoor Bluetooth Smart Watch for Android iPhone, 5 ATM Waterproof Tactical Watch, Rugged Fitness Tracker with Heart Rate/SpO2/AI Voice, Silver CUSTOMIZED FOR THE ADVENTURER: Our military smartwatch comes with 15 military-grade tests. Heat resistant to 187.96°F, cold resistant to -103.78°F, and enhanced 5ATM water resistance supports 50 meters underwater. This smartwatch with a Micro-blasted metal frame and titanium body. And comes with an extra camouflage band. NEVER MISS ANYTHING: The tough smart watch has a built-in Hi-Fi speaker and crystal-quality microphone. It supports Bluetooth to make, receive calls and play music. It is suitable for various sports modes indoors and outdoors. The tactical smart watch allows hands-free calling at home or while walking, running, cycling or hiking, freeing your hands from your phone. COMPREHENSIVE HEALTH MANAGEMENT: It is equipped with the latest BIO3.0 PPG high-precision optical sensor. The watch supports 24/7 blood oxygen, heart rate, monitoring. And automatic sleep tracking monitors your sleep status (deep sleep, light sleep, REM time). Truly achieve total health protection. BEST SPORTS PARTNE: Waterproof watch brings you 20 sports modes, such as walking, running, cycling, and mountaineering. The connects to your phone's GPS to track your movements to inspire your passion for sports. It also provides many features such as weather forecast, alarm clock, stopwatch, timer, etc. Additionally, the rugged fitness watch supports viewing text messages directly on your watch(such as Facebook, Twitter, Skype, etc.). HIGHER-LEVEL TECHNICAL SUPPORT: Compatible with Android 6.0/iOS 9.0 or higher and Bluetooth 5.0 or higher. Fully charge for 2 hours, use for 10 days+ or stand by for 40 days. Built-in 128MB flash memory gives you superfast storage so you can access what you need quickly. It's the best gift for men/him/dad/friends. PROFESSIONAL 24/7 AFTER-SALES SUPPORT: During the first connection of the watch, please follow the phone prompts to turn on all the permissions required for the smartwatch. If you encounter any problems during the purchase process, please feel free to contact us through Amazon. Our team of engineers provides 24/7 professional technical support! FRIENDLY REMINDER: When you get the smart watch, please charge it as soon as possible to activate the smartwatch, and it can be used normally when the watch is fully charged.(note: for sports use only)", 'image_url': 'https://m.media-amazon.com/images/I/41nCIVgk2uL._AC_.jpg', 'rating_number': 136, 'price': 35.99, 'average_rating': 4.0, 'parent_asin': 'B0BCF3KRMM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=24, version=1, score=0.7828453, payload={'preprocessed_description': "PlayBetter Garmin Instinct 2 Solar Tactical (Black) Rugged GPS Smartwatch | Power Bundle TPU Screen Protectors & Portable Charger | 2022 Men's Military Watch with Tactical Features | Large, 45mm [GARMIN INSTINCT 2 SOLAR TACTICAL POWER BUNDLE] - Garmin Instinct 2 Solar Tactical (2022 Model) Outdoor GPS Smartwatch, PlayBetter TPU Film Screen Protectors (4-Pack), Portable Charger (Large, 5000mAh) & USB Charging Cable [MILITARY-GRADE WATCH FOR YOUR MISSIONS] - This tactical watch provides unlimited battery life in smartwatch mode and 48 hours in GPS mode when charged for 3 hours in direct sunlight. Access dedicated tactical features and go dark with stealth mode to disable wireless communication and data sharing. [NON-STOP ACTIVITIES TO KEEP YOU ACTIVE] - This Garmin watch for men and women utilizes the power of 3-axis compass, altimeter, plus GPS, GLONASS and Galileo + access dedicated fishing, hunting activity, and more with its Connect IQ compatibility. [UNDERSTAND YOUR MIND AND BODY] - Let this heart rate monitor watch provide you with smart notifications + all-day health monitoring features to track your VO2 Max, heart rate, sleep, blood oxygen level, and more. Explore like no other with this smartwatch for men and women featuring built-in sports apps such as running, biking, swimming, strength training. [PERFECT OUTDOOR BUNDLE] - Keep your Instinct 2 fully charged and looking brand new with our high-definition TPU Film Screen Protectors and our large 5000mAh Portable Charger!", 'image_url': 'https://m.media-amazon.com/images/I/41DozEH81pL._AC_.jpg', 'rating_number': 123, 'price': 404.99, 'average_rating': 4.6, 'parent_asin': 'B0B5HN5RNC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=48, version=1, score=0.7502144, payload={'preprocessed_description': 'Leather Bands Compatible with Fitbit Versa 4/Versa 3/Sense 2/Sense, Classic Genuine Leather Replacement Wristbands Straps for Women Men Compatible Device: These silicone replacement bands compatible with Fitbit Versa 4/Versa 3/Sense 2/Sense, no device included. Fits for Wrist Size: 5.5" - 8.1" wrist. Soft Material: Bands are made of premium light and soft genuine leather with fashionable craftsmanship which will give ultra soft & comfortable touch feeling on your wrist. Install & Remove Easily: These bands fit as good as your Versa 4/Versa 3/Sense 2/Sense original band. It is easy to install and remove, no tools required! 180 Days No-hassle Warranty: Unconditionally refund or resend with any quality problems, life-time friendly customer service.', 'image_url': 'https://m.media-amazon.com/images/I/51XApx2YVoL._AC_.jpg', 'rating_number': 220, 'price': 9.99, 'average_rating': 4.2, 'parent_asin': 'B0C1CL9Y8T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=47, version=1, score=0.74635726, payload={'preprocessed_description': 'Wireless Earbuds with 4-Mic and Wireless Charging Case Waterproof 50H Playback Bluetooth Headphones LED Power Display Stereo Earphones, Touch Control in-Ear Headset with USB-C for Sports Work Black ', 'image_url': 'https://m.media-amazon.com/images/I/31hj5s1tJfL._AC_.jpg', 'rating_number': 853, 'price': None, 'average_rating': 4.2, 'parent_asin': 'B09V1F24X4'}, vector=None, shard_key=None, order_value=None)]